### ISSUE TITLE
comment_option operation with invalid percent_steem_dollars value

### ISSUE THREAD

**Issue by VIM-Arcange** [steemit/steem#2912] opened 2018-09-18 10:18 UTC
Below is a dump of transaction 24 in block 26037580

In the `comment_options` operation, the value of `percent_steem_dollars` is 55240, which means 552.40%

Shoudn't this kind of value (and the related transaction) be rejected?

```{
  "ref_block_num": 19763,
  "ref_block_prefix": 4048079810,
  "expiration": "2018-09-17T11:24:27",
  "operations": [
    [
      "comment",
      {
        "parent_author": "",
        "parent_permlink": "steempress",
        "author": "satoshinakamotob",
        "permlink": "moreworkrequiredtounderstandtheuserinuxsurveyshows-bh7xhkqmxc",
        "title": "More work required to understand the user in UX, survey shows",
        "body": " ... BODY CONTENT REMOVED ...",
        "json_metadata": "{\"community\":\"steempress\",\"app\":\"steempress/1.3\",\"image\":[\"\"],\"tags\":[\"steempress\",\"steem\"],\"original_link\":\"https://satoshinakamotoblog.com/more-work-required-to-understand-the-user-in-ux-survey-shows\"}"
      }
    ],
    [
      "comment_options",
      {
        "author": "satoshinakamotob",
        "permlink": "moreworkrequiredtounderstandtheuserinuxsurveyshows-bh7xhkqmxc",
        "max_accepted_payout": "1000000.000 SBD",
        "percent_steem_dollars": 55240,
        "allow_votes": true,
        "allow_curation_rewards": true,
        "extensions": [
          [
            0,
            {
              "beneficiaries": [
                {
                  "account": "steempress",
                  "weight": 1500
                }
              ]
            }
          ]
        ]
      }
    ],
    [
      "vote",
      {
        "voter": "satoshinakamotob",
        "author": "satoshinakamotob",
        "permlink": "moreworkrequiredtounderstandtheuserinuxsurveyshows-bh7xhkqmxc",
        "weight": 10000
      }
    ]
  ],
  "extensions": [],
  "signatures": [
    "202626a14a693ad7e27d0946cdd7ce28191057171c63416206172d3e1d703b91a72278830d3c40bfbc7732f5939507682d541a793e888a2f860ef8a9be1aff3b1c"
  ],
  "transaction_id": "42bd14ce5816595fb20f4484c0b8bcf71e75e1cb",
  "block_num": 26037580,
  "transaction_num": 24
}
```

**Comment by mvandeberg** [comment] 2018-09-18 16:12
Getting this block from my local node returns a reasonable value of 10000. However, https://steemd.com/b/26037580 shows a different value. More importantly, it shows a different value whenever you hit F5. I am guessing there is an uninitialized field when returning this object via API.

**Comment by VIM-Arcange** [comment] 2018-09-18 16:59
`curl -s --data '{"jsonrpc":"2.0", "method":"condenser_api.get_block", "params":[26037580], "id":1}' https://api.steemit.com`
returns the invalid value

**Comment by Jolly-Pirate** [comment] 2018-09-22 17:39
https://github.com/steemit/steem/issues/2807

**Comment by mvandeberg** [comment] 2018-09-24 17:02
Duplicate of #2807

**Closed by mvandeberg** 2018-09-24 17:02 UTC
Labels: 3, bug
