### ISSUE TITLE
cli_wallet exception on update_witness operation

### ISSUE THREAD

**Issue by pgarciagon** [steemit/steem#2873] opened 2018-09-07 06:08 UTC
When trying to to an update operation on the latest hf20 testnet (testnet-hf20-1535745600):

`unlocked >>> update_witness cervantes "http://www.steemit.com/@cervantes" TST75WxQfbDK6B5ksoJKrEzFV7vjHULkD9DckqBLmezhhg1hiPis3 {"account_creation_fee": "0.100 TESTS","maximum_block_size": 65536,"sbd_interest_rate": 000} true
update_witness cervantes "http://www.steemit.com/@cervantes" TST75WxQfbDK6B5ksoJKrEzFV7vjHULkD9DckqBLmezhhg1hiPis3 {"account_creation_fee": "0.100 TESTS","maximum_block_size": 65536,"sbd_interest_rate": 000} true`

I become the following error message:

> 1824058ms websocket_api.cpp:102         on_message           ] message: {"jsonrpc":"2.0","result":null,"id":4} 
1824063ms websocket_api.cpp:102         on_message           ] message: {"jsonrpc":"2.0","result":[{"id":162968,"name":"cervantes","owner":{"weight_threshold":1,"account_auths":[["tnman",1]],"key_auths":[["TST8HwSEc1yekg7phCnV2YbBWuYaPffboFU1yMePj5ZgUy3xi7fZU",1]]},"active":{"weight_threshold":1,"account_auths":[["tnman",1]],"key_auths":[["TST5J3D4qohrYbsmsUVPkXZupB3FKdwKhARQBaVBJgBHVEwkYuA6M",1]]},"posting":{"weight_threshold":1,"account_auths":[["buildteam",1],["steemauto",1],["streemian",1],["tnman",1]],"key_auths":[["TST5e784z4KkvvjwUaQ4WYx8uUNRga2hXL6Z63KByHqPEGAjdMc6U",1]]},"memo_key":"TST4whRSFMyWywt9bXS7WyX7Wz5vRHUbJvv8tEeapN3RvY8Bu5NcN","json_metadata":"{\"profile\":{\"profile_image\":\"https://cdn.steemitimages.com/0x0/https://cdn.steemitimages.com/DQmZBxqdcpDJNfNUdkV8mBHxQomTmfAXwQHaT6bvxbuJJJB/Cervantes_logo_final_Feb_2018-62.jpg\",\"name\":\"Witness cervantes\",\"about\":\"Working for the spanish speaking community\",\"cover_image\":\"https://s31.postimg.cc/5zyxe1yuj/Banner_Cervantes.png\"}}","proxy":"","last_owner_update":"2018-08-15T16:51:15","last_account_update":"2018-08-15T16:51:15","created":"2018-08-14T18:20:45","mined":false,"recovery_account":"porter","last_account_recovery":"1970-01-01T00:00:00","reset_account":"null","comment_count":0,"lifetime_vote_count":0,"post_count":18,"can_vote":true,"voting_manabar":{"current_mana":"15128290977","last_update_time":1536263358},"voting_power":9969,"balance":"64.225 TESTS","savings_balance":"0.000 TESTS","sbd_balance":"0.000 TBD","sbd_seconds":"0","sbd_seconds_last_update":"1970-01-01T00:00:00","sbd_last_interest_payment":"1970-01-01T00:00:00","savings_sbd_balance":"0.000 TBD","savings_sbd_seconds":"0","savings_sbd_seconds_last_update":"1970-01-01T00:00:00","savings_sbd_last_interest_payment":"1970-01-01T00:00:00","savings_withdraw_requests":0,"reward_sbd_balance":"0.000 TBD","reward_steem_balance":"0.000 TESTS","reward_vesting_balance":"0.000000 VESTS","reward_vesting_steem":"0.000 TESTS","vesting_shares":"15174.725638 VESTS","delegated_vesting_shares":"0.000000 VESTS","received_vesting_shares":"0.000000 VESTS","vesting_withdraw_rate":"0.000000 VESTS","next_vesting_withdrawal":"1969-12-31T23:59:59","withdrawn":0,"to_withdraw":0,"withdraw_routes":0,"curation_rewards":0,"posting_rewards":0,"proxied_vsf_votes":[0,0,0,0],"witnesses_voted_for":0,"last_post":"2018-09-05T21:05:45","last_root_post":"2018-09-05T21:05:45","last_vote_time":"2018-09-06T19:49:18","average_bandwidth":"157823444076","lifetime_bandwidth":"253790000000","last_bandwidth_update":"2018-09-06T19:49:18","average_market_bandwidth":1270000000,"lifetime_market_bandwidth":1270000000,"last_market_bandwidth_update":"2018-08-31T22:21:15","vesting_balance":"0.000 TESTS","reputation":0,"transfer_history":[],"market_history":[],"post_history":[],"vote_history":[],"other_history":[],"witness_votes":[],"tags_usage":[],"guest_bloggers":[]}],"id":5} 
1824066ms wallet.cpp:612                sign_transaction     ] v_approving_keys: ["TST5J3D4qohrYbsmsUVPkXZupB3FKdwKhARQBaVBJgBHVEwkYuA6M"] 
1824067ms wallet.cpp:615                sign_transaction     ] approving_key: TST5J3D4qohrYbsmsUVPkXZupB3FKdwKhARQBaVBJgBHVEwkYuA6M 
1824068ms websocket_api.cpp:102         on_message           ] message: {"jsonrpc":"2.0","result":{"head_block_number":252625,"head_block_id":"0003dad11bfb3c79a371df1f7cc35e4f6b545f03","time":"2018-09-06T20:30:21","current_witness":"init-8","total_pow":"18446744073709551615","num_pow_witnesses":0,"virtual_supply":"250839162.881 TESTS","current_supply":"250839162.881 TESTS","confidential_supply":"0.000 TESTS","current_sbd_supply":"0.000 TBD","confidential_sbd_supply":"0.000 TBD","total_vesting_fund_steem":"81118757.823 TESTS","total_vesting_shares":"29179831.883904 VESTS","total_reward_fund_steem":"0.000 TESTS","total_reward_shares2":"0","pending_rewarded_vesting_shares":"0.000000 VESTS","pending_rewarded_vesting_steem":"0.000 TESTS","sbd_interest_rate":1000,"sbd_print_rate":10000,"maximum_block_size":131072,"current_aslot":28219807,"recent_slots_filled":"340282366920938463463302549837730283519","participation_count":127,"last_irreversible_block_num":252604,"vote_power_reserve_rate":10,"average_block_size":2359,"current_reserve_ratio":200000000,"max_virtual_bandwidth":"528482304000000000000"},"id":6} 
10 assert_exception: Assert Exception
it != approving_account_lut.end(): 
    {}
    wallet.cpp:600 operator()
    {"auth_containers":[{"type":"witness_update_operation","value":{"owner":"cervantes","url":"http://www.steemit.com/@cervantes","block_signing_key":"TST75WxQfbDK6B5ksoJKrEzFV7vjHULkD9DckqBLmezhhg1hiPis3","props":{"account_creation_fee":{"amount":"100","precision":3,"nai":"@@000000021"},"maximum_block_size":65536,"sbd_interest_rate":0},"fee":{"amount":"0","precision":3,"nai":"@@000000021"}}}],"sigs":[]}
    transaction_util.hpp:103 verify_authority 

Following plugins are active:
`plugin = chain
plugin = webserver p2p json_rpc witness account_by_key tags follow market_history
plugin = database_api account_by_key_api network_broadcast_api tags_api follow_api market_history_api witness_api condenser_api block_api
plugin = account_history_rocksdb account_history_ap
`

The active key has been successfully imported via `import_key` and the account balances are also properly shown with `list_my_accounts`

**Comment by TimCliff** [comment] 2018-09-07 15:45
I have confirmed this issue is happening with the cli_wallet compiled from the `testnet-hf20-1535745600` branch when connecting to a testnet node.

After importing my active key (for account `timcliff2`), I called `unlocked >>> list_my_accounts` which works as expected:
```
timcliff2               0.000 TESTS             1.652370 VESTS        0.000 TBD
-------------------------------------------------------------------------
TOTAL                   0.000 TESTS             1.652370 VESTS        0.000 TBD
```

Any command which requires signing is failing though, with the same `verify_authority` error shown above:
`delegate_vesting_shares "timcliff2" "timcliff" "1.000000 VESTS" true`

```
10 assert_exception: Assert Exception
it != approving_account_lut.end():
    {}
    wallet.cpp:600 operator()

    {"auth_containers":[{"type":"delegate_vesting_shares_operation","value":{"delegator":"timcliff2","delegatee":"timcliff","vesting_shares":{"amount":"1000000","precision":6,"nai":"@@000000037"}}}],"sigs":[]}
    transaction_util.hpp:103 verify_authority
```

**Comment by mvandeberg** [comment] 2018-09-07 18:10
This is a duplicate of #68.

The tesnet adds an account auth the every account which then prevents them from using the CLI wallet.

**Comment by mvandeberg** [comment] 2018-09-07 18:10
@youkaicountry to close.

**Comment by youkaicountry** [comment] 2018-09-07 18:40
Closing as duplicate of #68.

**Closed by youkaicountry** 2018-09-07 18:40 UTC
Labels: 3, bug, project/hf20
