### ISSUE TITLE
libraries/fc/CMakeFiles/fc.dir/build.make:859: recipe for target 'libraries/fc/CMakeFiles/fc.dir/src/rpc/state.cpp.o' failed

### ISSUE THREAD

**Issue by bizlevel** [steemit/steem#2536] opened 2018-06-07 17:36 UTC
After make cli_wallet got error:

```
[ 66%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/rpc/cli.cpp.o
[ 66%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/rpc/http_api.cpp.o
[ 66%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/rpc/json_connection.cpp.o
[ 66%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/rpc/state.cpp.o
/usr/src/steem/libraries/fc/src/rpc/state.cpp: In member function ‘fc::rpc::request fc::rpc::state::start_remote_call(const string&, fc::variants)’:
/usr/src/steem/libraries/fc/src/rpc/state.cpp:47:69: error: no matching function for call to ‘fc::rpc::request::request(<brace-enclosed initializer list>)’
    request request{ "2.0", _next_id++, method_name, std::move(args) };
                                                                     ^
/usr/src/steem/libraries/fc/src/rpc/state.cpp:47:69: note: candidates are:
In file included from /usr/src/steem/libraries/fc/src/rpc/state.cpp:1:0:
/usr/src/steem/libraries/fc/include/fc/rpc/state.hpp:7:11: note: fc::rpc::request::request()
    struct request
           ^
/usr/src/steem/libraries/fc/include/fc/rpc/state.hpp:7:11: note:   candidate expects 0 arguments, 4 provided
/usr/src/steem/libraries/fc/include/fc/rpc/state.hpp:7:11: note: fc::rpc::request::request(const fc::rpc::request&)
/usr/src/steem/libraries/fc/include/fc/rpc/state.hpp:7:11: note:   candidate expects 1 argument, 4 provided
/usr/src/steem/libraries/fc/include/fc/rpc/state.hpp:7:11: note: fc::rpc::request::request(fc::rpc::request&&)
/usr/src/steem/libraries/fc/include/fc/rpc/state.hpp:7:11: note:   candidate expects 1 argument, 4 provided
libraries/fc/CMakeFiles/fc.dir/build.make:859: recipe for target 'libraries/fc/CMakeFiles/fc.dir/src/rpc/state.cpp.o' failed
make[3]: *** [libraries/fc/CMakeFiles/fc.dir/src/rpc/state.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:152: recipe for target 'libraries/fc/CMakeFiles/fc.dir/all' failed
make[2]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
CMakeFiles/Makefile2:4217: recipe for target 'programs/cli_wallet/CMakeFiles/cli_wallet.dir/rule' failed
make[1]: *** [programs/cli_wallet/CMakeFiles/cli_wallet.dir/rule] Error 2
Makefile:1099: recipe for target 'cli_wallet' failed
make: *** [cli_wallet] Error 2
root@steem:/usr/src/steem/build#
```

It is unresolved dependency?

**Comment by youkaicountry** [comment] 2018-06-07 18:54
What branch are you compiling from, and what OS version are you using?

**Comment by bizlevel** [comment] 2018-06-07 19:01
debian 8 x64, boost 1.60, cmake 3.2.2, berklydb5.13, master repo

**Comment by youkaicountry** [comment] 2018-06-07 20:40
Fair chance it's an unresolved dependency. Please make sure you have all dependencies installed as listed in https://github.com/steemit/steem/blob/master/doc/building.md, and boost properly installed

**Comment by youkaicountry** [comment] 2018-06-08 15:44
Since this is a build issue and not a bug, I'm closing it. Please consult the documentation for steemd and your distribution.

**Closed by youkaicountry** 2018-06-08 15:44 UTC

**Comment by pythonxyk** [comment] 2018-11-13 04:01
I have the same problem and  i have all dependencies installed , boost =1.60
can you tell me  which dependnice does not work

**Comment by fuzz-ai** [comment] 2018-11-30 07:13
I ran into this as well, though not when compiling from the top level.,  The solution seemed to be to use -std=gnu++14 in CXX_FLAGS

-std=c++11 didn't work.
