### ISSUE TITLE
Steem - Multi-language ?

### ISSUE THREAD

**Issue by Imadlekal** [steemit/steem#161] opened 2016-07-14 16:29 UTC
Hi there !

I speak both Arabic and French and I was wondering if there are any plans to make Steem a multi-language platform.
If it's the case then I'm ready to help , I googled little bit and couldn't find anything about on Transifex so please let me know !

**Comment by faddat** [comment] 2016-07-21 02:59
Seconded.  Speak Chinese (good luck cracking that market though)  and would like to open a portal in Vietnam.

**Comment by xeroc** [comment] 2016-07-21 06:36
A proposal about how it could be done:
https://steemit.com/steem/@noisy/how-to-make-80-population-of-the-world-happy-with-2-simple-features-and-1-line-of-code

**Comment by samupaha** [comment] 2016-07-21 07:38
I suggest a special tag for language using ISO 639-3: https://en.wikipedia.org/wiki/ISO_639-3

UI should have maybe a dropdown menu for most common languages, or a text field that will automatically suggest a language (and the proper code for it) when user starts to type it.

Assigning a wrong language tag for a post would be a good reason to downvote it. Users can also leave it blank if they are posting some encrypted messages or other data.

**Comment by mvandeberg** [comment] 2016-07-21 13:27
The blockchain itself only requires that comment body data be encoded in UTF-8. There are no restrictions on the characters contained in the comment body. Steemit.com may not render characters you want to use, but that doesn't mean you cannot use them through another application. As this is the repo for steemd, not steemit.com, I am going to close this issue. For the record, this is in no way says that we are not going to add support for other character sets, simply that it is not a blockchain level change.

**Closed by mvandeberg** 2016-07-21 13:27 UTC

**Comment by samupaha** [comment] 2016-07-21 14:05
This is not only a Steemit.com problem but also a Steem blockchain problem.

There should be a standard that specifies to UI in what language the message is written. If somebody wants to do Steem website for a certain language, he needs to know what messages are in that language. Without any language codes in posts this is quite hard to do, there needs to be some kind of AI that will determine language of every message.

I'm not a expert on the subject but I think that ISO 639-3 would be suitable standard for this. It contains pretty much all languages in the world, so there is need to change it later to some other standard. With it Steem can scale globally without problems.

**Comment by Vitalicus** [comment] 2017-06-12 22:29
I can translate any article, if author give me 5% of his article money :)

**Comment by TimCliff** [comment] 2017-06-13 14:36
The GitHub repository is not the appropriate place for this. It is intended to track changes to the Steem blockchain code. Please create a post on Steemit for this type of thing. @sneak to close.

**Comment by TimCliff** [comment] 2017-06-13 14:37
Sorry, misread. The issue is already closed.
