### ISSUE TITLE
node throws an error on api calls

### ISSUE THREAD

**Issue by ByronAP** [steemit/steem#268] opened 2016-08-14 19:27 UTC
As you can see below an error is being thrown which causes a database freeing. This happens over and over causing the node to become unresponsive with very little traffic.

UPDATED see error info in comment below

**Comment by ByronAP** [comment] 2016-08-14 19:56
even without the tags api error, the error with the database api constantly being freed remains

**Comment by ByronAP** [comment] 2016-08-14 20:31
`transactions from network on block 4084225
1807470ms th_a       database_api.cpp:180          database_api_impl    ] creating database api 12983057808
1807471ms th_a       websocket_api.cpp:88          on_message           ] message:
1807471ms th_a       websocket_api.cpp:132         on_message           ] e.to_detail_string(): 11 eof_exception: End Of File
stringstream
    {}
    th_a  sstream.cpp:109 peek

    {"str":""}
    th_a  json.cpp:478 from_string
1807471ms th_a       database_api.cpp:185          ~database_api_impl   ] freeing database api 12983057808`

**Comment by ByronAP** [comment] 2016-08-14 20:34
this actually appears to happen even on valid calls

**Comment by mvandeberg** [comment] 2016-08-15 14:16
Can you give an example of an API call over a websocket that causes this so that we can reproduce the issue?

**Comment by ByronAP** [comment] 2016-08-17 16:51
happens with every call

**Comment by abitmore** [comment] 2016-08-17 17:20
@ByronAP detailed commands/requests and responses please. It's perhaps caused by unneeded `\r` and/or `\n` at the end of request.

**Comment by abitmore** [comment] 2016-08-17 17:28
Or perhaps you're running a node with `--rpc-endpoint` and no firewall configured, so your RPC port is open to the world, and someone was testing the port (trying to hack your node). If this is the case, please setup a firewall to protect your node, or start node without `--rpc-endpoint`, or start node with `--rpc-endpoint 127.0.0.1:your_port_number`

**Comment by mvandeberg** [comment] 2017-01-24 21:15
The conversation on this issue is dead with no new information. We have not received any similar requests in some time so I am closing this issue.

**Closed by mvandeberg** 2017-01-24 21:15 UTC
