### ISSUE TITLE
p2p exception binding outgoing connection to desired local endpoint

### ISSUE THREAD

**Issue by robrigo** [steemit/steem#1276] opened 2017-07-24 12:21 UTC
Our steemd node is just crashed with the following error spamming the log:

`858307ms p2p        tcp_socket.cpp:162            bind                 ] Exception binding outgoing connection to desired local endpoint 0.0.0.0:46382: bind: Bad file descriptor`

Is this a familiar error or bug? Are there any known mitigations to it? I found this bitshares1 github issue thread that mentions it too: https://github.com/bitshares/bitshares1-core/issues/585

**Comment by mvandeberg** [comment] 2017-07-24 13:03
What OS are you running on?

I doubt that error is what caused the crash. If you have more of the console log prior to the crash, I may be able to help you.

**Comment by robrigo** [comment] 2017-07-24 14:15
Hey Michael,

We're on Ubuntu 16.04.2 and the logs prior to the spam of the aforementioned Exception were just high latency block production logs ... it seems as though the latency spiked and then this started happening.

**Comment by roadscape** [comment] 2017-07-24 14:29
https://github.com/steemit/steem/issues/277 indicates it could be a memory issue.

**Comment by robrigo** [comment] 2017-07-24 15:38
Hmmm weird, I've got plenty of RAM (8GB) and shared memory (16GB) on this instance.

Thanks for the idea though @roadscape.

**Comment by mvandeberg** [comment] 2017-07-24 15:43
#277 was pre-chainbase. I would not consider out of memory a problem that could cause this. As noted, in bitshares/bitshares1-core#585, older kernel versions could cause the error, but Ubuntu 16.04 has a new enough kernel, the error should not be caused by an old kernel.

I am more interested in seeing the actual logs just before the crash and a possibly a stack trace as I am not convinced this error message actually had anything to do with the crash.

Did the node crash because of a segfault, unhandled exception, or failed assertion?

**Comment by robrigo** [comment] 2017-07-24 17:02
@mvandeberg I've since lost that buffer and just now realized that the block production log is not written into the p2p logs, so I have unfortunately lost that information. Our node has been augmented to log the process so we will not lose this info going forward. Oops!

**Comment by theoreticalbts** [comment] 2017-07-28 14:45
I wonder if you might be running into an OS imposed file descriptor limit?

**Comment by youkaicountry** [comment] 2018-08-16 16:44
Fixed in #2779.

**Closed by youkaicountry** 2018-08-16 16:44 UTC
