### ISSUE TITLE
 Invalid token cannot 

### ISSUE THREAD

**Issue by Jasonpham139** [steemit/steem#2285] opened 2018-03-28 18:11 UTC
Hi there,

I registered with the account @jasonpham139 email address: jasonpham139@gmail.com and the verification e-mail came through, but I only saw it 2 weeks after it was sent. Now when I click on the link, it sends me to a steemit error page saying "Oops! Invalid token". My phone number says it's linked to an account so I cannot make another.  Cannot log into steemit chat. It will say username not found.

**Comment by mvandeberg** [comment] 2018-03-28 18:13
Duplicate of #2281 

Steemit.chat is not ran by Steemit and has different accounts than Steemit. In order the receive community support on Steemit.chat you will need to create an account. It does not have to be the same username you use on Steemit and we recommend using a different password for Steemit and Steemit.chat.

**Closed by mvandeberg** 2018-03-28 18:13 UTC
