### ISSUE TITLE
Inverted order prices & get_ticker quirks

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#131] opened 2016-06-30 22:00 UTC
##### `get_ticker` (market api)
 - ~~both `highest_bid` and `lowest_ask` appear to be inverted.~~
 - ~~`latest` stuck at 0.000~~
 - `sbd_volume` accurate but reported in satoshis (unlike the bid/ask)
 - ~~`highest_bid` and `lowest_ask` only return 3 decimals, but the book is often tight so would be good to have more~~

##### `get_order_book` (db api)
 - ~~price on *bid* side is flipped~~

##### `get_open_orders` (db api)
 - price on *bid* side is flipped

**Comment by abitmore** [comment] 2016-06-30 22:35
Duplicate of #124 ?

**Comment by roadscape** [comment] 2016-07-03 02:02
I need to check if 6fa9d49 fixed the `get_order_book` issue... but it's possible that only one side needed to be inverted.

The other functions do need adjustment though.

**Comment by roadscape** [comment] 2016-07-05 15:16
Updated OP with current status of bugs/requests.

**Comment by theoreticalbts** [comment] 2016-08-18 15:07
These commits have been merged. If this is still an issue, feel free to re-open or file a new ticket.

**Closed by theoreticalbts** 2016-08-18 15:07 UTC
