### ISSUE TITLE
Alarming drop in payout right at the moment of payout - by over $1,000 on a $1,250 post.

### ISSUE THREAD

**Issue by kentfrost** [steemit/steem#223] opened 2016-07-29 01:23 UTC
There were no unvotes or downvotes against my post - other users were able to confirm this.
Not sure if this expected behavior or not, but I certainly didn't expect it. 

I have a picture I took (to show my wife what the thread was garnering) taken at 3:01PM CST if it's needed. It showed at that time to be at $1,306.40. 
Just before the moment of payout, it was hovering around $1,250, give or take a few dollars. 
But, at the very second it went to pay out, it DROPPED to $190 according to steemstats.com, and the thread itself shows $143, which is the figure that was used to pay out. 
The SBD payout amount was set to be about $470, then dropped roughly 85%, leaving me with $71.754 at the very moment it went to pay me.

This is the post:
https://steemit.com/tag/@winstonwolfe/seriously-forget-about-the-money 
I know...ironic title. lol

Can anyone look into this and see if this is accurate, or perhaps a bug? 
If it is accurate then I will accept it. If not, I wanted to bring it to the attention to the developers so this doesn't happen to anyone else. 

Thank you for your time!!

**Comment by kentfrost** [comment] 2016-07-29 01:26
Here's the photo I took at 3:01PM CST.

http://i.imgur.com/Cgky3HU.jpg

**Comment by abitmore** [comment] 2016-07-30 00:27
As I commented in [this post](https://steemit.com/steemit/@winstonwolfe/lesson-learned-i-got-the-payout-i-deserved-get-your-post-perfect-before-posting-do-not-edit-it), the blockchain is working as intended. The UI should show related info though. So it's best to submit an issue to https://github.com/steemit/steemit.com/issues and close this one.

**Comment by theoreticalbts** [comment] 2016-08-17 14:45
This is actually an API issue.

**Comment by mvandeberg** [comment] 2017-01-24 21:08
The question is answered and there is no blockchain bug. The UI is constantly being updated to provide the clearest and most accurate information to the user.

**Closed by mvandeberg** 2017-01-24 21:08 UTC
Labels: platform, question
