### ISSUE TITLE
get_state promoted value is wrong for non-root categores

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#336] opened 2016-08-31 16:18 UTC
get_state /promoted/auction
returns: content.{username}/permlink.promoted: "0.010 SBD"

get_state /promoted/marketplace
returns: content.{username}/permlink.promoted:"10.020 SBD"

So it appears that in the non-root category promoted is taking the last promoted value and not summing but in the main category it is working fine.

![image](https://cloud.githubusercontent.com/assets/204121/18137052/8c111d40-6f6c-11e6-9581-7ab04ecec577.png)

![image](https://cloud.githubusercontent.com/assets/204121/18136821/b3636e08-6f6b-11e6-9d00-fc33bf40c4a6.png)

Reference:
https://steemit.com/steemit-bugs/@cryptojoy.com/promoted-post-problem-is-this-a-bug

**Comment by theoreticalbts** [comment] 2016-08-31 16:26
Investigating.

**Comment by theoreticalbts** [comment] 2016-08-31 16:59
I can't determine the exact cause, but I suspect #321.  That ticket was somehow closed without being merged, but I've merged it now.  Please try using current develop and `--replay-blockchain`, then post here whether the problem has gone away.

**Comment by theoreticalbts** [comment] 2016-08-31 17:20
Basically the way the tags plugin works is creating a "peer" object for each tag, which mirrors a subset of the comment data; i.e. a comment with `N` tags has `N+1` peer objects, one for each tag and additionally a "global" tag represented by the empty string.  This is what allows us to provide per-tag feeds: The peer objects are indexed by (tag, promoted_balance).

As a consequence, everything which changes the comment's fields needs to update all peer objects, to keep the invariant that the peer objects' fields have the same value as the comment's fields.  I think something is breaking this invariant, letting `mode` take different values for different peer objects of the same comment, which causes `promoted_balance` to get out of whack due to the check [here](https://github.com/steemit/steem/blob/10386ab489abc8795a9bd9f616dc5cdda5d5568f/libraries/plugins/tags/tags_plugin.cpp#L309-L310) which consults the `mode` of the peer object.

Really this code can be optimized by checking the comment's `mode` once, avoiding the entire loop for comments past the first payout window, which would workaround the problem -- but we really need to track down what's making the peer objects inconsistent. Which is why I'm asking @jcalfee to test it without the optimization, in order to gather some evidence relative to the question of whether the inconsistency is caused by #321 or something else.

**Comment by theoreticalbts** [comment] 2016-09-01 19:27
@jcalfee does the latest develop still have this bug?

**Comment by jcalfee** [comment] 2016-09-01 20:36
I'll need to find another post now...

**Comment by theoreticalbts** [comment] 2016-12-20 23:22
Closing due to age.

**Closed by theoreticalbts** 2016-12-20 23:22 UTC
