### ISSUE TITLE
Network crosstalk

### ISSUE THREAD

**Issue by Riverhead** [steemit/steem#612] opened 2016-11-26 03:34 UTC
With the release of 0.16.0rc3 a node mostly just reports crosstalk from other networks, currently golos. It is  impossible to debug node issues since nearly all messages are errors from excluded crosstalk blocks.

This is a request to have a node block, exclude, or otherwise suppress messages from other networks.

**Comment by BhuzOr** [comment] 2016-11-26 07:08
Would be nice to also fix the root cause #535

**Comment by mvandeberg** [comment] 2016-11-28 13:44
We have a plan to fix the issue, but it will take some time to upgrade everyone and deploy. The problem right now is that neither network are reporting their blockchain. We have to add that back into the protocol and then at a later date start requiring nodes be on the same network.

**Comment by mvandeberg** [comment] 2016-11-28 16:59
merged

**Closed by mvandeberg** 2016-11-28 16:59 UTC
