### ISSUE TITLE
Segfault during node shutdown

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#1154] opened 2017-06-03 17:48 UTC
steemd 0.18.2

```
2096518ms th_a       database_api.cpp:215          ~database_api_impl   ] freeing database api 35462736
2096525ms th_a       database_api.cpp:203          database_api_impl    ] creating database api 35462736
2096525ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc":"2.0","method":"get_owner_history","params":["shaka"],"id":0}
2096526ms th_a       database_api.cpp:215          ~database_api_impl   ] freeing database api 35462736
2097492ms th_a       database_api.cpp:203          database_api_impl    ] creating database api 35462736
2097493ms th_a       database_api.cpp:203          database_api_impl    ] creating database api 35381328
2097493ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc":"2.0","method":"get_dynamic_global_properties","params":[],"id":0}

Program received signal SIGSEGV, Segmentation fault.
0x0000000001009759 in decltype ((*((steemit::app::database_api::get_dynamic_global_properties() const::{lambda()#1}*)((decltype(nullptr))0)))()) chainbase::database::with_read_lock<steemit::app::database_api::get_dynamic_global_properties() const::{lambda()#1}>(steemit::app::database_api::get_dynamic_global_properties() const::{lambda()#1}&&, unsigned long) [clone .constprop.2966] ()
(gdb) bt
#0  0x0000000001009759 in decltype ((*((steemit::app::database_api::get_dynamic_global_properties() const::{lambda()#1}*)((decltype(nullptr))0)))()) chainbase::database::with_read_lock<steemit::app::database_api::get_dynamic_global_properties() const::{lambda()#1}>(steemit::app::database_api::get_dynamic_global_properties() const::{lambda()#1}&&, unsigned long) [clone .constprop.2966] ()
#1  0x0000000001009aae in steemit::app::database_api::get_dynamic_global_properties() const ()
#2  0x0000000000f83607 in std::_Function_handler<steemit::chain::dynamic_global_property_object (), void fc::vtable_copy_visitor<steemit::app::database_api>::operator()<steemit::chain::dynamic_global_property_object, steemit::chain::dynamic_global_property_object (steemit::app::database_api::*)() const>(char const*, std::function<steemit::chain::dynamic_global_property_object ()>&, steemit::chain::dynamic_global_property_object (steemit::app::database_api::*)() const) const::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#3  0x0000000000fea696 in std::function<fc::variant (std::vector<fc::variant, std::allocator<fc::variant> > const&)> fc::generic_api::api_visitor::to_generic<steemit::chain::dynamic_global_property_object>(std::function<steemit::chain::dynamic_global_property_object ()> const&) const::{lambda(std::vector<fc::variant, std::allocator<fc::variant> > const&)#1}::operator()(std::vector<fc::variant, std::allocator<fc::variant> > const&) const ()
#4  0x0000000000fea6cc in std::_Function_handler<fc::variant (std::vector<fc::variant, std::allocator<fc::variant> > const&), std::function<fc::variant (std::vector<fc::variant, std::allocator<fc::variant> > const&)> fc::generic_api::api_visitor::to_generic<steemit::chain::dynamic_global_property_object>(std::function<steemit::chain::dynamic_global_property_object ()> const&) const::{lambda(std::vector<fc::variant, std::allocator<fc::variant> > const&)#1}>::_M_invoke(std::_Any_data const&, std::vector<fc::variant, std::allocator<fc::variant> > const&) ()
#5  0x000000000151ba0d in fc::generic_api::call(unsigned int, std::vector<fc::variant, std::allocator<fc::variant> > const&) ()
#6  0x000000000151d04e in fc::generic_api::call(std::string const&, std::vector<fc::variant, std::allocator<fc::variant> > const&) ()
#7  0x000000000151d3b4 in fc::api_connection::receive_call(unsigned int, std::string const&, std::vector<fc::variant, std::allocator<fc::variant> > const&) const ()
#8  0x0000000001517fd7 in std::_Function_handler<fc::variant (std::string const&, std::vector<fc::variant, std::allocator<fc::variant> > const&), fc::rpc::websocket_api_connection::websocket_api_connection(fc::http::websocket_connection&)::{lambda(std::string const&, std::vector<fc::variant, std::allocator<fc::variant> > const&)#4}>::_M_invoke(std::_Any_data const&, std::string const&, std::vector<fc::variant, std::allocator<fc::variant> > const&) ()
#9  0x00000000015ca3ed in fc::rpc::state::local_call(std::string const&, std::vector<fc::variant, std::allocator<fc::variant> > const&) ()
#10 0x00000000015192f1 in fc::rpc::websocket_api_connection::on_message(std::string const&, bool) ()
#11 0x000000000151b321 in std::_Function_handler<std::string (std::string const&), fc::rpc::websocket_api_connection::websocket_api_connection(fc::http::websocket_connection&)::{lambda(std::string const&)#6}>::_M_invoke(std::_Any_data const&, std::string const&) ()
#12 0x00000000015891b6 in fc::detail::void_functor_run<fc::http::detail::websocket_server_impl::websocket_server_impl()::{lambda(std::weak_ptr<void>)#4}::operator()(std::weak_ptr<void>) const::{lambda()#1}::operator()() const::{lambda()#1}>::run(void*, {lambda()#1}) ()
#13 0x000000000149a0b3 in fc::task_base::run_impl() ()
#14 0x000000000149806e in fc::thread_d::process_tasks() ()
#15 0x00000000014982f6 in fc::thread_d::start_process_tasks(long) ()
#16 0x0000000001886b71 in make_fcontext ()
#17 0x0000000000000000 in ?? ()
(gdb)
```

**Comment by roadscape** [comment] 2017-06-20 17:53
0.19.0

```
2557179ms th_a       database_api.cpp:205          database_api_impl    ] creating database api 38619728
2557179ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc":"2.0","method":"get_account_count","params":[],"id":0}
2557180ms th_a       database_api.cpp:219          ~database_api_impl   ] freeing database api 38619728
2557183ms th_a       database_api.cpp:205          database_api_impl    ] creating database api 38619728
2557184ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc":"2.0","method":"get_reward_fund","params":["post"],"id":0}
2557184ms th_a       database_api.cpp:219          ~database_api_impl   ] freeing database api 38619728
2558174ms th_a       database_api.cpp:205          database_api_impl    ] creating database api 35860048
2558175ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc":"2.0","method":"get_dynamic_global_properties","params":[],"id":0}

Program received signal SIGSEGV, Segmentation fault.
0x000000000102f0f9 in decltype ((*((steemit::app::database_api::get_dynamic_global_properties() const::{lambda()#1}*)((decltype(nullptr))0)))()) chainbase::database::with_read_lock<steemit::app::database_api::get_dynamic_global_properties() const::{lambda()#1}>(steemit::app::database_api::get_dynamic_global_properties() const::{lambda()#1}&&, unsigned long) [clone .constprop.2978] ()
(gdb) bt
#0  0x000000000102f0f9 in decltype ((*((steemit::app::database_api::get_dynamic_global_properties() const::{lambda()#1}*)((decltype(nullptr))0)))()) chainbase::database::with_read_lock<steemit::app::database_api::get_dynamic_global_properties() const::{lambda()#1}>(steemit::app::database_api::get_dynamic_global_properties() const::{lambda()#1}&&, unsigned long) [clone .constprop.2978] ()
#1  0x000000000102f44e in steemit::app::database_api::get_dynamic_global_properties() const ()
#2  0x0000000000fab077 in std::_Function_handler<steemit::chain::dynamic_global_property_object (), void fc::vtable_copy_visitor<steemit::app::database_api>::operator()<steemit::chain::dynamic_global_property_object, steemit::chain::dynamic_global_property_object (steemit::app::database_api::*)() const>(char const*, std::function<steemit::chain::dynamic_global_property_object ()>&, steemit::chain::dynamic_global_property_object (steemit::app::database_api::*)() const) const::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#3  0x0000000001011656 in std::function<fc::variant (std::vector<fc::variant, std::allocator<fc::variant> > const&)> fc::generic_api::api_visitor::to_generic<steemit::chain::dynamic_global_property_object>(std::function<steemit::chain::dynamic_global_property_object ()> const&) const::{lambda(std::vector<fc::variant, std::allocator<fc::variant> > const&)#1}::operator()(std::vector<fc::variant, std::allocator<fc::variant> > const&) const ()
#4  0x000000000101168c in std::_Function_handler<fc::variant (std::vector<fc::variant, std::allocator<fc::variant> > const&), std::function<fc::variant (std::vector<fc::variant, std::allocator<fc::variant> > const&)> fc::generic_api::api_visitor::to_generic<steemit::chain::dynamic_global_property_object>(std::function<steemit::chain::dynamic_global_property_object ()> const&) const::{lambda(std::vector<fc::variant, std::allocator<fc::variant> > const&)#1}>::_M_invoke(std::_Any_data const&, std::vector<fc::variant, std::allocator<fc::variant> > const&) ()
#5  0x000000000154529d in fc::generic_api::call(unsigned int, std::vector<fc::variant, std::allocator<fc::variant> > const&) ()
#6  0x00000000015462ae in fc::generic_api::call(std::string const&, std::vector<fc::variant, std::allocator<fc::variant> > const&) ()
#7  0x0000000001546614 in fc::api_connection::receive_call(unsigned int, std::string const&, std::vector<fc::variant, std::allocator<fc::variant> > const&) const ()
#8  0x0000000001541b97 in std::_Function_handler<fc::variant (std::string const&, std::vector<fc::variant, std::allocator<fc::variant> > const&), fc::rpc::websocket_api_connection::websocket_api_connection(fc::http::websocket_connection&)::{lambda(std::string const&, std::vector<fc::variant, std::allocator<fc::variant> > const&)#4}>::_M_invoke(std::_Any_data const&, std::string const&, std::vector<fc::variant, std::allocator<fc::variant> > const&) ()
#9  0x00000000015f300d in fc::rpc::state::local_call(std::string const&, std::vector<fc::variant, std::allocator<fc::variant> > const&) ()
#10 0x0000000001542d31 in fc::rpc::websocket_api_connection::on_message(std::string const&, bool) ()
#11 0x0000000001544d61 in std::_Function_handler<std::string (std::string const&), fc::rpc::websocket_api_connection::websocket_api_connection(fc::http::websocket_connection&)::{lambda(std::string const&)#6}>::_M_invoke(std::_Any_data const&, std::string const&) ()
#12 0x00000000015b1e06 in fc::detail::void_functor_run<fc::http::detail::websocket_server_impl::websocket_server_impl()::{lambda(std::weak_ptr<void>)#4}::operator()(std::weak_ptr<void>) const::{lambda()#1}::operator()() const::{lambda()#1}>::run(void*, {lambda()#1}) ()
#13 0x00000000014c3eb3 in fc::task_base::run_impl() ()
#14 0x00000000014c1eae in fc::thread_d::process_tasks() ()
#15 0x00000000014c20f6 in fc::thread_d::start_process_tasks(long) ()
#16 0x00000000018a2e71 in make_fcontext ()
#17 0x0000000000000000 in ?? ()
```

**Comment by mvandeberg** [comment] 2018-08-02 17:10
Closing, unable to reproduce

**Closed by mvandeberg** 2018-08-02 17:10 UTC
