### ISSUE TITLE
condenser_api.get_comment_discussions_by_* not showing certain posts

### ISSUE THREAD

**Issue by amosbastian** [steemit/steem#2853] opened 2018-08-29 13:47 UTC
I am not sure if this is technically a bug, but it's very weird unless I am missing something obvious. I found [a post](https://steemit.com/coogger/@hakancelik/coogger-api-update-coogger-python-v021-how-to-use-coogger-python) that isn't showing under https://steemit.com/created/utopian-io despite having the "utopian-io" tag. There was one [other post](https://steemit.com/utopian-io/@crokkon/what-is-the-reward-pool-share-of-vote-sellers-bid-bots-and-autovotes-1535479520399) this happened to, and the only thing I found in common between the two was that they both had more than 5 tags (the latter post has since been edited to remove the additional tags).

#### Expected behaviour
Going to https://steemit.com/created/utopian-io should show all posts with "utopian-io" as one of its tags.

#### Actual behaviour
Going to https://steemit.com/created/utopian-io does not show all posts with "utopian-io" as one of its tags.

#### How to reproduce
I encountered this when using [beem](https://github.com/holgern/beem) and the following code:
```python
from beem.discussions import Query, Discussions_by_created
query = Query(limit=100, tag="utopian-io")
for post in Discussions_by_created(query):
    print(post)
```
but you can also simply go to https://steemit.com/created/utopian-io for example and see if you can find [this post](https://steemit.com/coogger/@hakancelik/coogger-api-update-coogger-python-v021-how-to-use-coogger-python). It shows under all `/created/<tag>` where `<tag>` is one of its tags, except the tag "utopian-io". Other posts with 5 tags or fewer (e.g. [this one](https://steemit.com/git/@emrebeyler/writing-efficient-commit-messages-software-projects-and-utopian)) will show on `/created/utopian-io` despite the first tag being "git", for example.

I created [this post](https://steemit.com/test/@sttest2/testing-something-1535549753448) with "utopian-io" as its 6th tag, and it's not showing under `/created/utopian-io`. I also created [this post](https://steemit.com/utopian-io/@sttest1/testing-something-1535550008190) with "utopian-io" as its 1st tag and "hyphenated-tag" as its 6th tag, and once again it's not showing under `/created/utopian-io`, but is showing under `/created/hyphenated-tag`.

**Comment by TimCliff** [comment] 2018-08-29 14:03
Probably a dupe of 
https://github.com/steemit/steem/issues/852

**Comment by amosbastian** [comment] 2018-08-29 14:11
@TimCliff it shows on their profile, though - in the above cases it's only happening when querying a specific tag, name "utopian-io".

**Closed** 2021-11-19 09:39 UTC
