### ISSUE TITLE
Self-Reward Attack: Up to 1% liquid steem p. week with 5 forged accounts

### ISSUE THREAD

**Issue by riensen** [steemit/steem#316] opened 2016-08-25 12:16 UTC
# Attack
An attacker can generate significant additional financial reward (>1%) via self-rewarding.

Any large SP accounts (>5.000 Vests) generate about 1/10000 in curation reward per upvote. (Note: The larger the amount of SP the higher the ratio due to non-linear scaling).

This equals ~1/10000*~20*7= ~1.14% per week in liquid assets which is higher than what a power down generates per week. 

This opens up an easily executable attack:

1. Create 5 forged accounts
2. Each account posts 4 times a day = 20 posts
3. Attacker upvotes each post
4. Make sure each post is semi-useful while being (mostly) auto-generated. Example:
   * Statistics (Daily SBD rewards, SP changes per day, Most Active Traders ....)
   * Posts that curate other Posts (e.g. Algorithm on Blockchain that finds posts with certain properties - high follower count but low payout)
   * Recipes read from APIs of cooking websites
   * Link to other websites e.g. News Aggregator
   * Existing Blog Posts which are replacing some words with synonyms (e.g. google translate english->dutch->english)

Step 4 is critical. If the posts are blatantly low quality than the scheme could get exposed and accrue downvotes. However, as long as they offer a minimal amount of value any upvote is justified and unlikely to be counteracted with downvotes. This is especially true since a downvote would appear to damage the author who would seem like an innocent bystander in the above scenario.

An attacker can also make this easier by just getting paid by the author for votes e.g. half of all SBD rewards.

The above attack may already be executed at the moment as it is hard to uncover.

# Proposed Solution: Voting Power per Author
Each Curator has Voting Power in relation to any other Author. Voting Power decreases significantly with each repetitive vote on the same author e.g. high penalty per vote which only recovers fully over 7 days.

### Implementation
The implementation could be more simplified than general voting power to save computation: 
WEEK_CONST = 7\*24\*60\*60;
author_voting_power = time_since_last_vote_on_author_in_sec/(WEEK_CONST);
author_voting_power = author_voting_power > 1 : 1 ? author_voting_power;

### Result
* Above attack is severely more difficult with the given solution. An attacker would need to impersonate some 140 accounts instead of just 5 accounts which all need to generate semi-useful content in possibly different areas of topics (otherwise risking exposure). 
* Paying for votes would get more difficult as the attacker needs to trust 140 account instead of just 5 "buddys". The risk of getting exposed would increase significantly.
* Positive side-effect: More diversity of authors on Trending.
* Positive side-effect: Higher Distribution of SBD and SP.

**Comment by bytemaster** [comment] 2016-08-25 16:25
Cost of this implementation is a table that grows N^2 the number of accounts in the system.

Potential mitigating changes:

1. increase the minimal payout from $0.02 to $1.00 makes this attack more difficult / impossible for smaller accounts.
2. reduce the target number of votes per day each account can give with 100% power from 50 to 10
3. implement measures to counter the voting influence of the steem power behind the attacker.

Increasing the number of accounts required to pull off the attack could make it harder to detect the attack, but it would still exist.

Other mitigating circumstances...  what percent of daily rewards are being allocated to said attacker?   If the posts were making significant payouts then it would get far more attention and risk exposing the whales behind it.  

We should expect and tolerate some level of abuse so long as it isn't so rampant that it detracts from everyone else in a perceptible way.

**Comment by theoreticalbts** [comment] 2016-08-25 16:56
I don't know where you're getting the 1/10000 per upvote figure.

Looking at [my own account](http://steemroll.io/api-explorer/#method=get_account_history&params=[%22theoretical%22,%224470%22,%2230%22]) you can see that I get about 30 VESTS for curation reward when nobody else upvotes.

    >>> get_account_history theoretical 4470 30

This account has approximately 60 million VESTS, so the return per upvote is therefore about 5 x 10^-7 times its stake.  The soft limit is currently 40 votes / day, which gives us an annualized rate of return of:

    5 x 10^-7 x 40 x 365 = .0073

Author rewards are 3x curation rewards, so the annualized return for self-upvoting, including author rewards, is 2.92% per year.

There are two other effects which will further mitigate this attack:

- Obvious abuse can be downvoted to remove its rewards.
- Steem is still operating "hotter" than its long-term temperature, i.e. we're still in the "hyperinflation" period. Thus, rewards measured as a percentage of the total STEEM supply / total market cap have been dropping, and will continue to drop (i.e. the system will "cool"), which will decrease rewards for everyone (assuming the market cap stays the same).

You explain in your post about marginally useful posts which manage to attract some others' upvotes do offer a higher rate of return, and then propose a system to counteract this effect.  As @bytemaster notes this will consume lots of resources, and additionally it will be possible to Sybil attack.

But this proposal has a more fundamental flaw: Those posts *are* being judged useful by some members of the community, and the higher rate of return *is* justified.  The only way the system can judge what provides value is on the basis of upvotes, and you're saying that some posts which get upvoted don't actually provide as much value as the upvotes imply.

This is exactly how the system is supposed to function.  When there's not enough genuine high-quality original content, to the extent that autogenerated copy-pasta keyboard mashes can earn upvotes, then the system should naturally attract more authors capable of generating content that can out-compete the garbage.  Essentially the upvotes that are currently going to garbage are a resource that anyone capable of generating better content will be able to claim -- which will create a rewards-fueled, competition-driven virtuous cycle of attracting authors and increasing content quality.

**Comment by theoreticalbts** [comment] 2016-08-25 16:57
I'm closing this, since the system is functioning exactly as designed.

**Closed by theoreticalbts** 2016-08-25 16:56 UTC

**Comment by riensen** [comment] 2016-08-25 19:50
> I don't know where you're getting the 1/10000 per upvote figure.

I am talking about very large accounts with some 5000M Vests the size of e.g. "mottler" these generate a larger percentage which equals up to 1/10000.
