### ISSUE TITLE
Killing steemd with SIGINT results in seg fault

### ISSUE THREAD

**Issue by Phistr90** [steemit/steem#197] opened 2016-07-22 08:23 UTC
Every time I kill the steemd with SIGINT signal I get a seg fault and the next time I start steemd I have to do an replay since it was shut down 'unclean'.

**Comment by taoteh1221** [comment] 2016-07-22 12:43
I can confirm same issue on a lower-end minipc on Ubuntu 14.04 (quad core 2.18 GHz Celeron, 8Gb ram). Almost never exits cleanly.

**Comment by theoreticalbts** [comment] 2016-08-17 18:42
Duplicate of #142.

**Closed by theoreticalbts** 2016-08-17 18:42 UTC
