### ISSUE TITLE
steemd crashes after rpc call

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#566] opened 2016-11-09 10:43 UTC
Unfortunately, as a side effect of listening on rpc endpoint during replay #565
it is possible to cause crash by sending valid rpc call
`curl -sd '{"id":0,"method":"call","params":[0,"get_state",["trending"]]}' $RPC`
leading to unusable blockchain data as in #542 and forcing to start over again.

I could provide coredump through some more suitable channel (size)

**Comment by Gandalf-the-Grey** [comment] 2016-11-09 12:50
Update: Unfortunately that's the case for normal node operation too, i.e. after resync/replay.

**Comment by mvandeberg** [comment] 2016-11-09 14:02
On the horizon for steemd with Chainbase is a full read write lock implementation. It is already implemented in Chainbase, we simply need to wrap all of our API calls with a read lock. That will prevent the problems you are describing.

**Comment by theoreticalbts** [comment] 2016-11-09 15:26
I originally thought this is a duplicate of #355 but that is not the case.  This API call is not broadcasting a transaction.

@mvandeberg I disagree. I think what this indicates is that there is something incorrect about our API handling, but it is masked by the fact that steemd is usually idle.  The replay is simply a conveniently available environment which sends blocks / tx's at the node as fast as it can which unmasks the bug.

**Comment by roadscape** [comment] 2016-11-09 21:38
Do you have a backtrace?

**Comment by mvandeberg** [comment] 2016-11-10 14:12
Do any other APIs work?

What plugins are enabled?

**Comment by Gandalf-the-Grey** [comment] 2016-11-10 19:57
Just for the record:  That was a good lead, crash seems to occur while trying to access indices managed by not enabled plugin.

**Comment by mvandeberg** [comment] 2016-11-11 18:12
The temporary fix to this was to add the indices on plugin creation. All plugins are constructed regardless of whether they are enabled and the logic to connect them to signals is in other methods. The disadvantage to this method is that it is no longer possible to determine if a plugin was enabled on a previous version of the database. I am considering adding `plugin_object` to the object database as a way of determining if the enabled plugin has historical records or not.

**Closed** 2016-11-12 16:19 UTC
