### ISSUE TITLE
full node - unexpected, occassional slow start from saved state

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#1477] opened 2017-08-31 08:43 UTC
Use case scenario:
Running full node with all bells and whistles
```
du -h /run/fullnode/shared_memory.bin
108G    /run/fullnode/shared_memory.bin
```
Performance notes: `shared_memory_file` is on `tmpfs`, backed by 64GB physical RAM, swapped to RAID1 on SSDs when needed. Dedicated machine, `Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz`
Replay finishes after 5 hours so it's relatively good for this job.
I'm stopping node. After short time (a minute or three) starting it back up again.
```
3322023ms th_a       block_log.cpp:130             open                 ] Log is nonempty
3322023ms th_a       block_log.cpp:139             open                 ] Index is nonempty
```
hangs at that ^ state for considerable amount of time
```
616596ms th_a       database.cpp:2569             show_free_memory     ] Free memory is now 12G
```
it continues roughly after 15 minutes (!)
huge swap in/out = huge disk IOs

Sometimes it goes much quicker (115 seconds). I don't have statistics what's more frequent because it's pretty rare scenario to shutdown a node, however it might also affect startup time in auto-scalling environments that are using saved state at creation of new instances.

**Comment by mvandeberg** [comment] 2017-08-31 20:44
`invalidate_invariants` is called on open. It may be the cause of this pause.

**Comment by mvandeberg** [comment] 2017-09-04 14:30
I think we should make the `invalidate_invariants` check conditional on startup with a `--validate-database-invariants` startup flag.

**Comment by mkochanowicz** [comment] 2017-09-05 14:08
@mvandeberg you probably mean `validate_invariants` - `invalidate_invariants` not exists

**Comment by mvandeberg** [comment] 2017-09-05 14:31
Yes, I do. Thanks for catching my mistake.

**Comment by mvandeberg** [comment] 2017-09-13 00:54
Some of the slowness should be alleviated now. If the problem persists, let me know.

Closing for now.

**Closed by mvandeberg** 2017-09-13 00:54 UTC
Labels: status/WIP
