### ISSUE TITLE
Cant send funds

### ISSUE THREAD

**Issue by jaka87** [steemit/steem#1868] opened 2017-12-09 10:02 UTC
Here is a script I use 

```
 pass =localStorage.active;
  memo='test xy';
  steem.broadcast.transfer(pass, 'jaka87', 'boomerang', '0.01 SBD', memo, function(err, result) {
  console.log(err, result);
});
```

In response I get 

```
"10 assert_exception: Assert Exception
false: invalid symbol
    {}
    th_a  database.cpp:3472 get_balance

    {"op":["transfer",{"from":"jaka87","to":"boomerang","amount":"0.01 SBD","memo":"test xy"}]}
    th_a  database.cpp:2892 _apply_transaction

    {"trx":{"ref_block_num":40023,"ref_block_prefix":3471448718,"expiration":"2017-12-09T09:58:18","operations":[["transfer",{"from":"jaka87","to":"boomerang","amount":"0.01 SBD","memo":"test xy"}]],"extensions":[],"signatures":["2020173637dbd7ee9ef59142fa84e68edbe0cd6500cca97fe58af03bc7d5a007d5665007359f03d83f0da23b575af952f595f375f24a68eab9426282a8b7ec45a7"]}}
    th_a  database.cpp:2896 _apply_transaction

    {"trx":{"ref_block_num":40023,"ref_block_prefix":3471448718,"expiration":"2017-12-09T09:58:18","operations":[["transfer",{"from":"jaka87","to":"boomerang","amount":"0.01 SBD","memo":"test xy"}]],"extensions":[],"signatures":["2020173637dbd7ee9ef59142fa84e68edbe0cd6500cca97fe58af03bc7d5a007d5665007359f03d83f0da23b575af952f595f375f24a68eab9426282a8b7ec45a7"]}}
    th_a  database.cpp:660 push_transaction

    {"call.method":"call","call.params":[3,"broadcast_transaction_synchronous",[{"ref_block_num":40023,"ref_block_prefix":3471448718,"expiration":"2017-12-09T09:58:18","operations":[["transfer",{"from":"jaka87","to":"boomerang","amount":"0.01 SBD","memo":"test xy"}]],"extensions":[],"signatures":["2020173637dbd7ee9ef59142fa84e68edbe0cd6500cca97fe58af03bc7d5a007d5665007359f03d83f0da23b575af952f595f375f24a68eab9426282a8b7ec45a7"]}]]}
    th_a  websocket_api.cpp:124 on_message"


```
It did work couple of weeks ago but not any more. Any idea ?

**Comment by mvandeberg** [comment] 2017-12-09 18:07
Assets must list full precision. `0.010 SBD` instead of `0.01 SBD`.

Closing as this is not a bug in steemd.

**Closed by mvandeberg** 2017-12-09 18:07 UTC
