### ISSUE TITLE
Remove decimal_places from smt_setup_operation and update existing code

### ISSUE THREAD

**Issue by Kiwonik** [steemit/steem#1659] opened 2017-10-16 14:12 UTC
Once `smt_create_operation` was introduced, its `smt_name` field of type `asset_symbol_type` contains not only a numeric asset identifier (NAI) but also precision digits, which means that:
a) SMT precision is set at its creation and can not be changed later.
b) Separate precision fields in all other smt operations are redundant and misleading now.

See also comments to issue #1654

**Comment by mvandeberg** [comment] 2017-10-16 14:19
No, I want to keep the precision in the setup operation.

The available NAI returned by `get_next_smt_identifier` are not bound to a precision. The API call does that at run time so that the user does not have to think about what the last character should be. As a precaution, I want the precision to be there twice and fail the op in validation if they don't match.

**Comment by mvandeberg** [comment] 2017-10-16 14:19
Separate precision fields in other ops, other than `smt_create_operation`, can be removed.

**Comment by vogel76** [comment] 2017-10-16 15:35
How comment above (related to unbound NAIs returned by get_next_smt_identifier) corresponds to conclusions made here:
https://github.com/steemit/steem/issues/1654
Maybe we should have separate class to represent NAI and next inherit asset_symbol_type from it, to extend NAI by precision. Then will be clear: if opt takes a NAI, it holds pure identifier, if asset_symbol_type the NAI + precision.

**Comment by mvandeberg** [comment] 2017-10-16 15:40
No, the reason we are doing it this way is to have a single representation that the user needs to know of. The binary serialization already had both NAI and precision. This change only impacts the string serialization.

**Comment by Kiwonik** [comment] 2017-10-16 19:41
@mvandeberg in your 1st comment you say to keep precision in the **setup** operation, and in the 2nd one you're OK with removing it in operations other than `smt_create_operation`, which seems to contradict the former. 
I'm reading your intention as to keep precision/decimal field in `smt_create_operation` (the initial one) and remove it from all subsequent operations (including `smt_setup_operation`). Is this correct?

**Comment by mvandeberg** [comment] 2017-10-16 19:43
I apologize, I was confused. Keep explicit precision in `smt_create_operation`. All other ops don't need precision, unless it was intended that precision could be changed pre-launch. @theoreticalbts, thoughts?

**Comment by youkaicountry** [comment] 2018-09-05 20:08
Closing as outdated.

**Closed by youkaicountry** 2018-09-05 20:08 UTC
Labels: project/smt_v05, question
