### ISSUE TITLE
class template partial specialization is not more specialized than the primary template

### ISSUE THREAD

**Issue by kenneth** [steemit/steem#2270] opened 2018-03-25 12:01 UTC
fc error?

```
In file included from /steemit/steem/libraries/schema/include/graphene/schema/schema_types/static_variant.hpp:7:
/steemit/steem/libraries/fc/include/fc/static_variant.hpp:385:34: error: class template partial specialization is not more specialized than the primary
      template [-Winvalid-partial-specialization]
  template<typename... T> struct get_typename<T...>  { static const char* name()   { return typeid(static_variant<T...>).name();   } };
                                 ^
/steemit/steem/libraries/fc/include/fc/reflect/typename.hpp:18:30: note: template is declared here
  template<typename T> class get_typename{};
                             ^
1 error generated.
make[2]: *** [libraries/schema/CMakeFiles/graphene_schema.dir/schema.cpp.o] Error 1
make[1]: *** [libraries/schema/CMakeFiles/graphene_schema.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by theoreticalbts** [comment] 2018-03-26 15:11
Duplicate of #2204

**Closed** 2018-03-26 20:10 UTC
