### ISSUE TITLE
Discussion - Open the possibility to rel=canonical

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/steem#2647] opened 2018-07-17 00:59 UTC
With plugins like SteemPress and the multiplication of UIs based on Steem, I think it would be important to start implementing rel=canonical. 

All parties would benefit.

For example, when I write on my blog using SteemPress, there is no sure way that Google will take the one on my blog to be the original one...most likely Google will side with the behemoth that is Steemit.com

It is the same for all UIs developing on the Steem Blockchain, they are competing against steemit.com for SEO and it negatively impacts everyone.

If there was an automatic:

<link rel="canonical" href="/original-app-the-content-was-created" />

Then the problem would be solved once and for all to everyone's benefit.

**Comment by themarkymark-steem** [comment] 2018-07-17 03:33
Steemit already has rel canonical, but it is set to Steemit.com which makes the problem worse.  I have brought this up a few times and it's a good chance this is one of the reasons Engadget doesn't post anymore.

It really would be nice to have this customizable in json_metadata.

**Comment by mac128k** [comment] 2018-07-17 03:50
Closing as a duplicate of https://github.com/steemit/condenser/issues/336

**Closed by mac128k** 2018-07-17 03:50 UTC
