### ISSUE TITLE
"Done reindexing" without reindexing while running explicitly with `--reindex`

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#1605] opened 2017-09-28 10:17 UTC
"Done reindexing" without reindexing while running explicitly with `--reindex`

After unexpected hardware restart I've lost (obviously) `tmpfs` content holding
`shared_memory.bin` and `shared_memory.meta` (as `shared-file-dir` was pointing there)

After bringing back my server online I used:
`./bin/steemd-v0.19.2 -d gtg --replay --flush=1000000`

```
2884110ms th_a       database.cpp:197              reindex              ] Done reindexing, elapsed time: 0.00260200000000000 sec
```
then of course:
```
2889612ms th_a       main.cpp:198                  operator()           ] Started witness node on a chain with 1 blocks.
2889740ms th_a       block_log.cpp:204             append               ] 10 assert_exception: Assert Exception
index_pos == sizeof( uint64_t ) * uint64_t( b.block_num() - 1 ): Append to index file occuring at wrong position.
    {"position":126834672,"expected":8}
    th_a  block_log.cpp:194 append
2889742ms th_a       database.cpp:2691             _apply_block         ] 10 assert_exception: Assert Exception
index_pos == sizeof( uint64_t ) * uint64_t( b.block_num() - 1 ): Append to index file occuring at wrong position.
    {"position":126834672,"expected":8}
    th_a  block_log.cpp:194 append
rethrow
    {}
    th_a  block_log.cpp:204 append

    {}
    th_a  database.cpp:3108 update_last_irreversible_block
```

Expected behavior: `--replay` forces reindexing.

**Comment by mvandeberg** [comment] 2017-09-28 14:17
Related to #1414

Because it was an unexpected hardware restart, I am guessing that it crashed while writing to the block log. If the last 4 bytes were 0x000000, then when reindexing it would assume there was a single block. But when attempting to resync afterwards, appending did not occur as expected, resulting in the error message seen above.

**Comment by mvandeberg** [comment] 2018-09-13 17:04
Closing, can't reproduce.

**Closed by mvandeberg** 2018-09-13 17:04 UTC
