### ISSUE TITLE
cli_wallet list_my_accounts only list one account

### ISSUE THREAD

**Issue by moisesmcardona** [steemit/steem#1246] opened 2017-07-10 14:50 UTC
After using the create_account_delegated command, it creates the account and I can see the keys, but I can't see the account listed when using list_my_accounts. I tried importing the Active Key using the import_key command but it still doesn't show when listing accounts. Am I missing something or is this a bug?

**Comment by mvandeberg** [comment] 2017-07-10 14:59
This is a duplicate of #1194

It was fixed and merged, but has not been deployed to production.

**Closed by mvandeberg** 2017-07-10 14:59 UTC
Labels: duplicate
