### ISSUE TITLE
Random Witness steemd Crashes?

### ISSUE THREAD

**Issue by klye-dev** [steemit/steem#533] opened 2016-10-26 15:33 UTC
Hey guys. Just reporting in some weird behavior from my witness node this morning. 
Seems my steemd running only the witness plugin crashed earlier giving me the following error:

> steemd: /root/steem/libraries/fc/src/thread/thread_d.hpp:361: bool fc::thread_d::start_next_fiber(bool): Assertion `non_preemptable_scope_count == 0' failed.
> Aborted (core dumped)

Any idea what's causing this? I've got 8gb of RAM and it's not using nearly that much it seems so I'm unsure as to why she dumped/crashed like that.

Also to be noted is that it buggered up the chain I had on disk and wouldn't let me use --replay-blockchain to boot off of it again. I had to download and transplant a new copy of the blockchain to get it to go again.

Thanks guys, Great work on the project so far.

<3 @klye

**Comment by theoreticalbts** [comment] 2016-12-21 00:03
Duplicate of #586

**Closed by theoreticalbts** 2016-12-21 00:03 UTC
