### ISSUE TITLE
Witness Replay Stalls During 1st Sync

### ISSUE THREAD

**Issue by propertunist** [steemit/steem#1667] opened 2017-10-18 20:13 UTC
I have recently setup a witness server for the first time and used the guide that is recommended in the witness chat group: https://steemit.com/steem/@someguy123/your-guide-to-setting-up-a-witness-server-steem-in-a-box-hf19

I find that when I run the replay process, everything goes ok until around the 16 millionth block in the syncing process, at which point the process just stops without any error in the logs. I have repeated the replay several times and waited many hours to see if it will recover, but it doesn't. I asked around in the witness group on steem chat and got some tips, but none of them have resolved the issue.

The server has 16 cores and 92GB of RAM, plus over 100GB of storage space - so capacity should not be an issue here. Ubuntu 16.4 is being used.

Has anyone seen this before? Is there a debugging guide for this kind of issue available anywhere? 
thanks

**Comment by Gandalf-the-Grey** [comment] 2017-10-18 23:26
> _"I find that when I run the replay process, everything goes ok until around the 19 millionth block"_

Which is very unlikely currently for Steem because:
`"head_block_number": 16450654`

**Comment by propertunist** [comment] 2017-10-19 00:39
16450654 = 16 million 450 thousand and 654.. so that's 16 million+

the shared-file-size is 48G

**Comment by propertunist** [comment] 2017-10-19 00:39
oh. lol.. i meant to type 16 millionth, not 19 millionth

**Comment by propertunist** [comment] 2017-10-19 00:42
i got a bit more progress on the sync process by restarting the docker container, but it quickly got stuck again and now restarting the process achieves nothing. the block is currently stuck at: 16441035

**Comment by mvandeberg** [comment] 2017-10-19 13:18
Can you post any sort of logs from your container?

(i.e. `docker logs --tail 100` )

**Comment by itsmikechu** [comment] 2017-10-30 17:30
I'm stalled / stuck on my replay as well.  

I should probably throw more AWS memory at this box then restart the container.

`...
   63.7873%   10500000 of 16460965   (4383M free)
   64.3948%   10600000 of 16460965   (4323M free)
342359ms th_a       database.cpp:3620             apply_hardfork       ] HARDFORK 17 at block 10629455
343144ms th_a       database.cpp:3620             apply_hardfork       ] HARDFORK 18 at block 10629486
   65.0023%   10700000 of 16460965   (4291M free)
   65.6098%   10800000 of 16460965   (4291M free)
   66.2173%   10900000 of 16460965   (4403M free)
   66.8248%   11000000 of 16460965   (4490M free)
   67.4323%   11100000 of 16460965   (4565M free)
   68.0398%   11200000 of 16460965   (4637M free)
   68.6473%   11300000 of 16460965   (4745M free)
   69.2547%   11400000 of 16460965   (4794M free)
   69.8622%   11500000 of 16460965   (4873M free)
   70.4697%   11600000 of 16460965   (4840M free)
   71.0772%   11700000 of 16460965   (4808M free)
   71.6847%   11800000 of 16460965   (4728M free)
   72.2922%   11900000 of 16460965   (4621M free)
   72.8997%   12000000 of 16460965   (4530M free)
   73.5072%   12100000 of 16460965   (4423M free)
   74.1147%   12200000 of 16460965   (4323M free)
   74.7222%   12300000 of 16460965   (4234M free)
   75.3297%   12400000 of 16460965   (4173M free)
898342ms th_a       database.cpp:2569             show_free_memory     ] Free memory is now 3G
   75.9372%   12500000 of 16460965   (4092M free)
   76.5447%   12600000 of 16460965   (3907M free)
   77.1522%   12700000 of 16460965   (3694M free)
   77.7597%   12800000 of 16460965   (3475M free)
   78.3672%   12900000 of 16460965   (3213M free)
[ec2-user@ip-172-31-28-234 steem-docker]$ `

**Comment by itsmikechu** [comment] 2017-10-30 18:52
Same effect even after bumping up the memory.

![image 2017-10-30 at 12 48 58 pm](https://user-images.githubusercontent.com/2320216/32189648-0302f10a-bd71-11e7-94f2-08d1ad51bb47.png)

**Comment by mvandeberg** [comment] 2017-10-30 22:50
How long are you letting it reindex before killing the process?

**Comment by Gandalf-the-Grey** [comment] 2017-10-31 00:04
@itsmikechu What AWS instance is this?

**Comment by itsmikechu** [comment] 2017-10-31 09:55
@mvandeberg Thanks for the follow up.  I was letting it sit for approx 2 hours with the same log output.  Later yesterday evening, I came back and found that it had completed the replay with <1GB to spare which is what's the server is running with this morning: https://cl.ly/013P2g2L3m1L

@Gandalf-the-Grey I started out with a t2.large and I'm now using t2.xlarge. I think the guide I was using might have been dated, and if I had read the README like I was supposed to, I would have seen that a minimum of 16GB of memory is now required.  I'm going to run with this instance type for now, but I may need to bump it up to t2.2xlarge. 

Sorry for the excess noise and thank you for the help.

**Comment by propertunist** [comment] 2017-11-04 18:24
In my case, I found that the problem was somehow related to the docker container/code since when I built steem manually and ran the process without docker it all worked correctly, first time.

**Comment by hrosspet** [comment] 2018-01-26 12:52
> In my case, I found that the problem was somehow related to the docker container/code since when I built steem manually and ran the process without docker it all worked correctly, first time.

I can confirm this is unfortunately still true.

**Comment by Gandalf-the-Grey** [comment] 2018-01-26 22:46
@hrosspet Hard to guess without any meaningful data about your deployment, versions, system, etc.
If what you quoted is true, then it's good news because it was some 3rd party container.
Use official one and provide more data about your case if problem persist.

**Comment by hrosspet** [comment] 2018-01-27 10:18
@Gandalf-the-Grey 

> If what you quoted is true, then it's good news because it was some 3rd party container.

What I quoted is true, but it wasn't some 3rd party container, it was the official docker from steemit. It was built with docker on an aws r4 instance running up-to-date Ubuntu 16.04.

**Comment by mvandeberg** [comment] 2018-09-13 17:28
Closing, can't reproduce.

**Closed by mvandeberg** 2018-09-13 17:28 UTC
