### ISSUE TITLE
JSON needs escapping

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#340] opened 2016-09-01 14:37 UTC
The following is unparsable JSON as returned by `wscat`:

```
> {"id":13,"method":"call","params":[0,"get_content",["xeroc","re-piston-20160818t080811"]]}
< {"id":13,"result":{"id":"2.8.653012","author":"xeroc","permlink":"re-piston-20160818t080811","category":"piston","parent_author":"xeroc","parent_permlink":"piston","title":"","body":"\u0000\u0001\u0002\u0003\u0004\u0005\u0006\a\b\t\n\u000b...
```

Escape sequences like `\u0000` and `\t` should instead be `\\u0000` and `\\t`.

An example: http://stackoverflow.com/questions/39273039/parsing-all-possible-utf-8-values-in-a-json-string

**Comment by theoreticalbts** [comment] 2016-09-01 17:55
> Escape sequences like \u0000 and \t should instead be \\u0000 and \\t.

No, they shouldn't.  On the steemit.com ticket, @tpchap made a useful comment:  "BTW SteemWatch crashed with invalid character 'a' in string escape code if it helps anybody."

The problem is that according to [here](http://www.json.org/) the following escape sequences are valid JSON:

    \" \\ \/ \b \f \n \r \t \uxxxx

According to [here](https://en.wikipedia.org/wiki/Escape_sequences_in_C#Table_of_escape_sequences) the following escape sequences are valid in C:

    \a \b \f \n \r \t \v \\ \' \" \? \nnn \xhh

where `\nnn` is octal and `\xhh` is hex escapes.

The escape sequences emitted by FC [here](https://github.com/steemit/fc/blob/360d86da80b79445fa43b29369d918d1fd5759ac/src/io/json.cpp#L508-L584) are:

    \a \b \f \n \r \t \\ \" \uxxxx

We see that `\a` escape sequence is emitted even though it is not valid JSON, so FC needs to be patched.

So really there are two bugs here:

- (a) FC emits `\a` which is not strictly compliant JSON and not accepted by many parsers.
- (b) The UI doesn't know what to do when a post contains certain control characters, e.g. characters in the `\u0000` to `\u001f` range.

(a) is clearly an fc bug which I'll fix shortly.  I consider (b) to be a UI issue -- if the browser displays junk when these control characters are added to a DOM element, then the UI needs to decide whether to let junk be displayed, or whether / how to sanitize the characters.  Basically:

- A post can contain any UTF-8 characters.
- The API's will return a JSON string of the UTF-8 characters, i.e. the `body` of the above post is correct except for the presence of the `\a` character.
- If the UI needs certain characters to be escaped before they are fed to the Markdown / HTML handlers or inserted into the DOM, then it is responsible for escaping the characters.

**Comment by jcalfee** [comment] 2016-09-01 18:33
It is not about display.. It is invalid serialization of json because it is not escaped.
```python
python3
>>> import json
>>> json.dumps({"body": "\u0000"})
'{"body": "\\u0000"}'
>>> json.loads('{"body": "\u0000"}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 11 (char 10)
```

**Comment by theoreticalbts** [comment] 2016-09-01 18:51
That's because you're specifying the JSON in Python as a string literal.  It needs escaped in this case, yes, but that's because otherwise an actual \u0000 would be inserted in the JSON string.  Maybe this example will clarify things for you:

     $ cat test.json
    {"body":"\u0000"}
    $ python3 -c 'import json; print(json.load(open("test.json", "r")))'

If you want to stick with pure Python, you can use a raw string to treat the backslash as literal:

    python3
    >>> import json
    >>> json.loads(r'{"body": "\u0000"}')

If we want to talk about hex, the hex dump of the correct serialization looks like this:

    $ hd test.json
    00000000  7b 22 62 6f 64 79 22 3a  22 5c 75 30 30 30 30 22  |{"body":"\u0000"|
    00000010  7d 0a                                             |}.|

The correct serialization has a *single instance* of character `5c`.  This single character is *represented in string literal* with two backslashes, but it is *displayed* as a single backslash when the string literal is printed (unless you use something like `repr()` which formats the string as a string literal instead of displaying it).

**Comment by theoreticalbts** [comment] 2016-09-01 18:56
In particular, I think you're getting confused when you do

    >>> json.dumps({"body": "\u0000"})
    '{"body": "\\u0000"}'

the problem is that you're working in Python's REPL which evaluates an expression and shows the value of that expression using `repr()` (unless it is `None`, in which case nothing is shown).  If you instead use `print()` to display the output, you'll see something which may be less confusing to you:

    >>> print(json.dumps({"body": "\u0000"}))
    {"body": "\u0000"}

**Comment by jcalfee** [comment] 2016-09-01 20:44
Your file example is very interesting.  I'll look into how that might be possible in JavaScript.  I have a hunch I'll have to hack it with by doing a regex replace on \\u\d{4} ... to add the escape slash..

**Comment by theoreticalbts** [comment] 2016-09-01 21:02
I think what you actually want to do is as simple as

    // escape_sequence_lut is a global variable initialized once at startup
    escape_sequence_lut = {"\u0000" : "\\u0000", "\u0001" : "\\u0001", ..., "\u001f" : "\\u001f"}

    // this code processes each character of the body
    new_body = ""
    for( c in body )
    {
        if( (c >= "\u0000") && (c <= "\u001f") )
            new_body += escape_sequence_lut[c];
        else
            new_body += c;
    }

If you want some characters to come through (for example, tabs and newlines), you can just have those characters map to themselves in `escape_sequence_lut` (for example "\u000a" : "\u000a", "\u000d" : "\u000d").

**Comment by theoreticalbts** [comment] 2016-09-01 21:02
Reopening this until I get the actual FC issue fixed.

**Comment by jcalfee** [comment] 2016-09-08 14:18
It appears to be fixed using only the change to FC.  I did not need to make any changes to the steemit.com code after all.  I can view http://localhost:3002/piston/@xeroc/piston with the latest steemd.  This post has the test utf-8 comment in it.  Still broken at steemit.com though, I assume we need to upgrade.

**Comment by mvandeberg** [comment] 2017-04-14 18:53
Closing because #342 handles escaping characters in FC properly.

**Closed by mvandeberg** 2017-04-14 18:53 UTC
