### ISSUE TITLE
Restore Long Term Payouts

### ISSUE THREAD

**Issue by willbanks** [steemit/steem#267] opened 2016-08-14 09:11 UTC
A recent hardfork change removed the ability for postings to payout after 30 days.
This has had the net effect of incentivizing "right now" clicks instead of "future clicks".
In otherwords content is being skewed towards what will payout quickly rather than efforts that may take a long time to pay off.  Attracting whales right now, vs putting up what we know and what we love and working on building a strong following in our own right.

That means anyone who wants to monetize their content long term will eventually use the platform to advertise their content which is hosted on other platforms, rather than keeping their content on steemit.

Ask yourself what you would rather see 5 years from now.  A blockchain full of content that was relevant 5 years ago, full of shock and awe tactics and clickbait?  Or a blockchain chock full of quality content, the kind of content that might take a person days, weeks or months to create. 

A blockchain which contains the very first books by the next J.K. Rowling, Stephen King, or even the next Stephen Hawking? Books we can still read for free. A place where we still support our favorite authors with nothing more than an upvote?

I explained it to Stan here...

https://steemit.com/bitshares/@stan/cryptonomex-rears-its-head#@williambanks/re-stan-re-williambanks-re-stan-cryptonomex-rears-its-head-20160814t013249242z

I brought this up because he mentioned issues getting VC attention.  I think VCs would be extremely excited about this because it completely changes the ballgame for content publishing.

My explanation got upvotes from stan, michaelx & kenny-crane so it doesn't look like I'm alone in the wilderness here.

After researching the issue further, I understand the change was made to prevent blockchain bloat both from the daily payouts and the fact that the content itself can get quite extensive.  So perhaps the content itself could be stored in IPFS and the blockchain would simply store an IPFS link instead of the content directly.  This would also allow content to be edited and updated long after the 24hrs cutoff while reducing the impact on the blockchain overall.

Therefore this issue is a feature request asking you to allow payments for upvotes on content every 30 days or whatever, and if needed, facilitate this by storing the content in <a href="https://ipfs.io/">IPFS or similar</a>.

If you do this, I can bring a large group of authors to the platform, plus I think the science nerds on the site would start using it for prepress, basically eliminating the need for https://arxiv.org/ for those of us who publish there (seems to be about 10 of us at the moment, but we can bring friends).

**Comment by indykpol** [comment] 2016-08-15 19:16
I wholeheartedly second that comment. I did not realise payouts are limited to the first 30 days. This is a real shame. I am one of those science nerds, as well as photographer. I thought I could make a photo blog with stories from around the world that would eventually pay me something, but realisng the 30-day limitation, this really puts me off.

**Comment by NateBrune** [comment] 2016-08-17 03:27
Hi I also agree that 30 day payments should be added back in. Having content that is valuable for long into the foreseeable future is in itself valuable for the steem blockchain. It increases quality on the whole. Take https://steemit.com/steem/@arhag/how-supercomputing-was-able-to-dominate-the-mining-queue-and-how-the-bug-was-fixed for example. This post will be valuable to people long long down the line. It would be a real shame if arhag wasn't able to benefit from his post-quality after 30 days.

**Comment by aaroncox** [comment] 2016-08-17 07:34
This is a fundamental question related to "what is steemit designed to do?" as far as I understand. 

As I see it, there's two schools of thought within the community:

1. Steemit.com is a transient information hub (like reddit, twitter, etc). Information is not meant to be permanent, it's meant to have a relatively short lifespan and relevant for a few days.
2. Steemit.com is a permanent information hub (like wordpress, medium, etc). Information is designed specifically to be long-lasting, SEO rich and engaging for long periods of time.

You can't use medium.com to post tweets on, and you can't write blog posts on twitter.  You also don't set up a wordpress site for your reddit posts or write blog posts on reddit. None of that makes sense because the content doesn't perform well within the defined parameters of those systems. The rules in place are designed to enhance the site's primary goal.

Right now the majority of the systems, including: 

- The limit of 2 payouts (24hr payout + 30d payout)
- Curation rewards limitations (only curation rewards on the 1st payout)
- Editing restrictions (no editing past 1st payout) 
- Sorting algorithms (sorting by 24hr payouts on the homepage) 

These all strengthen **Option #1** and reinforce the idea of a short-lived content site. @NateBrune, even your [screem application](https://github.com/NateBrune/Screem) is designed with Option #1 in mind. The only thing Option #2 has going for it is that we have the option to do very rich and sophisticated content types. The entire rest of the interface screams (pun intended) Option #1.

I don't think realistically it's wise to switch back to continual 30 day payments unless the decision is made that steem/steemit is a long term, rich, seo optimized content site. Right now a lot of decisions (good or bad) seem to be focusing on short term content. 

My personal opinion is that I'd rather see a stronger focus on the long term content. It's inherently more valuable and easier to monetize than short term content.

**Comment by matthewniemerg** [comment] 2016-08-17 12:23
I think that removing curation reward limitations to the 1st payout severely limits an author's ability to both be discovered and fails to incentivize users who find good content after the first payout but do not want to upvote as they are not rewarded. 

Disclaimer: I do upvote good content after I find it, on occasion, even if it is not completely advantageous to me.

**Comment by andulolika** [comment] 2016-08-17 12:47
This is a good idea, not being able to update/improve your posts as time goes by (and new knowledge reaches you) is really unconvenient.

**Comment by indykpol** [comment] 2016-08-17 12:51
> andulolika commented 2 minutes ago
> This is a good idea, not being able to update/improve your posts as time goes by (and new knowledge reaches you) is really unconvenient.
This issue is not about it - it's about allowing payouts after 30 days, and not about allowing post edits after this period.

**Comment by andulolika** [comment] 2016-08-17 14:35
Hmm alright, sorry for that, I still support this tho, It wouldn't allow posts to be seen after a while which would render the utility of the site into nothing. I just got a decent idea :P I'll be posting it soon.

**Comment by theoreticalbts** [comment] 2016-08-17 15:12
Anything related to payouts is consensus, so post objects have to be kept in memory as long as they could potentially be upvoted and paid out. The reason for the 30-day window is to allow old posts to be archived -- get them out of the database. Our memory usage is already getting uncomfortably large; requiring everyone to keep everything back to the beginning of time will be counterproductive.

**Comment by andulolika** [comment] 2016-08-17 15:46
While I see your point isn't that the point of a blockchain?

**Comment by samupaha** [comment] 2016-08-17 16:12
@aaroncox you have correctly analyzed the situation.

I'm personally also more inclined for long term content, but I can see why most people might want to have more short term stuff. The attention span of an average internet user is very short nowadays.

My ideal solution for the situation would be to have a few different blockchains (working as sidechains). They would have different reward schemes that encourage certain types of content creation.

- Fresh content. Twitter-like short messages, memes, breaking news, video streaming. If content is older than 24 hours, very few are interested in it anymore.
- Blog-like content. Essays, opinions, commentary, longer news articles, etc. Stays relevant from a few days to a few months. Almost like Steem is now, but adjusted a little bit on the longer term side.
- Book-like content. Long texts. Stays relevant for years.

With these three blockchains Steem would dominate blockchain based social media.

I'm not sure if it's possible or feasible, but maybe different reward systems could even work in one blockchain. I guess it might get too complex.

**Comment by aaroncox** [comment] 2016-08-17 18:09
@theoreticalbts - Thank you for that, that's a useful bit of knowledge and reasoning behind some of the decisions regarding payouts and timelines. 

@samupaha - I love this idea and I'd be interested in exploring the idea further. Breaking it into 3 particular divisions each with it's own governing rules makes a lot of sense. Different content types definitely have different types of lifespans and it makes sense to treat them that way. It would also be great to be able to move posts between the chains in the case of mis-posts and spam, to help combat the memory usage concerns. 

The idea of specific chains for specific content types doesn't immediately resolve the problem, but it does help add some clarity and focus on the goals steemit.com. 

I don't think anyone is opposing the idea of rewarding long term content in general, it's just a matter of "is it appropriate in this instance" from a technical standpoint.

**Comment by Markrmorrisjr** [comment] 2016-08-18 00:24
As one of the aforementioned authors, this is a huge part of what drew me here. If there is no residual income and my content stays published here forever, there is virtually no value in developing any kind of content on this site in the hopes of making income from it. Since very, very few, and fewer as the platform expands, can hope to have the $1000.00+ posts that are the dream, having a decent shot at being discovered later was a large part of  my strategy. With this no longer being the case, myself and the two dozen other writers I brought with me, need to rethink. Throwaway content is the only logical thing. Is Steemit prepared to become the Buzzfeed of the blockchain world? because that is exactly what will happen. I guess I missed the part in the white paper, with all of its high flown freedom talk, and libertarian bent, where it said this is a dictatorship where decisions of this nature can be made unilaterally. That being said, I am not a tech person, per se, I do better than the average schlub, due to years of slogging through writing platforms, etc, but I don't understand the intricacies of the storage, etc. I only know that this is not at all the vision that is presented in the white paper, and certainly not the assumption anyone is making. I sell shit anywhere. I don't need something as complex as Steemit to get that done.

**Comment by Alifton** [comment] 2016-08-18 00:48
@Markrmorrisjr

> Is Steemit prepared to become the Buzzfeed of the blockchain world? because that is exactly what will happen.

Actually it would already seem, this is very much the situation as it stands right now.  The big question moving forward is, can and will it be fixed before a majority of the"Good" and "Original" content creators jump ship in lieu of greener pastures?

**Comment by Markrmorrisjr** [comment] 2016-08-18 00:55
Well, when we do, we leave behind whatever we thought we were building here. For me, it's not worth it if that is the game. I can already build new content to sell everyday. I came here to create something more that might last. Fuck this.

**Comment by Markrmorrisjr** [comment] 2016-08-18 01:16
Here is a piece I wrote about it, I don't think many even realize this is a thing. https://steemit.com/steemit/@markrmorrisjr/an-open-letter-to-steemit-gods-dan-in-particular-are-you-trying-to-build-the-buzzfeed-of-the-blockchain if you would, upvote it, I don't care about the money, I just want this to be known. I found out by accident and have a serious decision to make about pursuing any more publishing on Steemit.

**Comment by Alifton** [comment] 2016-08-18 01:25
@theoreticalbts Uhm, not buying this part one bit...

>The reason for the 30-day window is to allow old posts to be archived -- get them out of the database. Our memory usage is already getting uncomfortably large; requiring everyone to keep everything back to the beginning of time will be counterproductive.

I call shenanigans because the very principle of a blockchain is that it is able to archive everything starting at the very beginning from whence it came.  If the problem is simply indexing it in a database then making it easier to query with less stress on your server, maybe it's time to put some of the massive amounts of reserved capital to good use, and make use a data center like every other major platform of this proposed magnitude.  The entire "print" library of congress would fit into 15TB and all of twitter from it's inception would fit into 20TB.

Source : <a href=https://blogs.loc.gov/digitalpreservation/2012/04/a-library-of-congress-worth-of-data-its-all-in-how-you-define-it>The Library of Congress Article On Digital Preservation</a>

Saying it's a memory issue is simply a cop out and a total an attempt to convince the less tech savvy that long term accessible storage is expensive, RAM is out of the question, and that renting or maintaining a server rack is an unreasonable expectation.  The Steemit blockchain does not store pictures, audio, video or anything that is storage intensive right now.  Having personally analyzed the blockchain, as of right now it only stores plain text.

----------------------------------------------
I'm not buying it for one second.  If that was truly a real issue, then big data centers couldn't exist because they would simply be too cost prohibitive which they obviously are not.  Nice try on using a false scapegoat as a cop-out excuse, but anyone here who has any experience with big data knows that : 

> requiring everyone to keep everything back to the beginning of time will be counterproductive.

the above statement simply is not true.  
--------------------------------------------

Feeding people BS however, IS counterproductive.  I store the entire Steemit blockchain on a flash drive right now.  In fact I can fit the entire 2 years worth of the Ethereum blockchain on a flashdrive right along side Steemit's and still have room for plenty of future blocks from both chains.

I'm not buying this excuse for even a nanosecond, and neither will anyone one else with common sense and even a basic understanding of how big data works...

**Comment by Markrmorrisjr** [comment] 2016-08-18 02:05
Thanks for sharing that. I wondered, but I wasn't sure. I thought that was how it worked and part of the beauty of the system. Of course, perhaps it is more about the access than the actual storage of content. Memory could be an issue in more than one way, right?

**Comment by Alifton** [comment] 2016-08-18 02:25
@Markrmorrisjr 
When we're talking about a platform who's posts have been known to reward some people with upwards of $10k plus in a single day?  Nope, it's just a matter of putting that money to good use.  

Trust me I've worked in IT for many years, lectured at GDG (Google Developers Group) Devfest in Fresno, 2013. I've also also attended many other lectures on Big Data, and know exactly how easy (not to mention cheap) it is to rent, or even buy and maintain a big data server.

$10k would be more than enough to last this platform for a very long time to come.  Especially if one takes into account the $180 million dollar market cap of just STEEM, not to mention Steem Dollars?  Servers are barely a drop in that size of a bucket.  Which is why I called shenanigans.

Source : https://coinmarketcap.com/currencies/steem/

**Comment by Markrmorrisjr** [comment] 2016-08-18 02:52
Makes sense to me. I'm not doubting your credentials, or knowledge, by the way, just trying to understand. So, here's my question, then, what value is there in shuffling content into a cyber store room never to be seen again, unless, of course, someone from outside Steemit searches for it? I can't see any value to the platform and you're saying the excuses being presented are not valid, any other idea as to what the benefit is? Perhaps the design is to shift rewards toward new users to encourage growth?

**Comment by Alifton** [comment] 2016-08-18 04:07
@Markrmorrisjr 
I can only speculate as to the motivations behind the curtain but money is typically a very powerful motivator if I had to guess.  While it's true archival of data that isn't accessed regularly or quickly is much cheaper than keeping it live and available 24/7, the typical mitigating factor is a simple cost analysis.

Think of it in terms of the insurance company methodology of risk, vs cost analysis.  The movie Fight Club did a great monologue and summary of how this process works.  If it's cheaper to pay out a few big claims in the short term than it is to spend a little extra money to secure the infrastructure for the long term, that is typically the route most companies choose. The big picture is rarely factored in when it comes to a simple bottom line cost analysis report because it's simply just that, a basic short term cost analysis and not a profit projection analysis for the next several foreseeable years.  The problem in doing so is that short term savings have a risk potential when it comes to long term survival, as would be the case for Steemit.  Saving a few bucks now could cost them big money farther down the road if users start to migrate away from the platform in favor of a better business model.

Don't get me wrong this platform is still in beta and is going through growing pains right now.  I have no idea what the future of Steem holds, I just know how to smell a lame excuse from a mile away.  Especially one that makes me feel uncertain about its ethicacy and raises questions about the integrity of a such a statement that is most certainly was known to be false by the claimant.

Maybe it was an oversight, maybe I misinterpreted the rational, or maybe someone realized that they're not the only smart one on this thread?  On these things I could only speculate and would rather just stick to the facts of the matter at hand.

**Comment by samupaha** [comment] 2016-08-18 06:00
@Alifton Steem blockchain is based on Graphene which works differently than other blockchains: https://bitshares.org/technology/industrial-performance-and-scalability/

**Comment by Alifton** [comment] 2016-08-18 07:27
@samupaha I'm well aware of Steem being Graphene based.  

None of that address the simple fact that claiming that there's a lack of computing resources is a bit of a stretch.  The biggest claim of BitShares, and Steemit were the ability to scale and process transactions at an extraordinary rate using minimal hardware resources.  

None of this would explain a statement like we're running out of memory because that's a hardware issue not a software issue and hardware can easily be scaled with something as simple as a credit card.  Graphene is more than capable of processing massive amounts of data, an it's software meant to run with minimal overhead..  The software being used has nothing to do with a refusal to raise the bar for the hardware on which it is run.

**Comment by Markrmorrisjr** [comment] 2016-08-18 11:08
Well, whatever the reason, if someone wants to attract many, many, many high quality indie authors, build a clone and provide ongoing residual payouts, because you'll have them coming out your ears in a few months. There are writers the quality of Stephen King and the like grinding away on sites that pay nothing, believing they aren't ready to publish yet that write for upvotes when those upvotes could be putting groceries on the table through a system like this, but even if the upvotes don't pay, if the content just goes into oblivion, but still stays there to compete with their own new premium content, I cannot see them being a part of this long term.

**Comment by aaroncox** [comment] 2016-08-18 11:31
After reading this, it felt like things got way too amp'd up. I'm not sure where the competitive attitudes are coming from lately. 

@Alifton I run a few full nodes of steem, so I'm just sharing my experiences to shed some personal experiences on the memory issues. On my servers, the memory requirements right now are growing fast. The `steemd` processes on my nodes right now are eating about 7gb of RAM each, and when I started (about a month ago) it was 5gb each. 

My understanding is that while a post is eligible for "payout" (the 24hr/30day windows), it's always loaded in RAM for each node. At least that's what I took from @theoreticalbts speaking about it earlier in this thread. 

The requirements for full nodes are increasing right now - and even if this change had a minor impact on that growing RAM, it would be a step in the wrong direction until whatever is eating all the RAM gets optimized.

@Markrmorrisjr I haven't really seen anyone disagree with wanting payouts to occur further in the future. A few reasons have been thrown out as to why technically it would be difficult, but no one's jumping out immediately and saying it's a bad idea. I'd say the vast majority of people want these windows to be extended. I said I prefer long-life content over short in my OP yesterday.

It may also not be a top priority right now - but maybe it should be. People want security in knowing that their efforts will be worth something in the future. I totally get this. I think the direction we need here is to have constructive dialogs about the actual problems and potential solutions.

It's all one big grand experiment. We can change things, but things shouldn't just be changed because someone wants it and wants it now. Those kneejerk reactions cause unwanted side effects, which we've already seen happen.

**Comment by Markrmorrisjr** [comment] 2016-08-18 11:42
This is fair. I'm not trying to be kneejerk at all,  but understand, I literally power this computer I am typing on by selling my words, and putting them somewhere where they stay forever, but lose all future potential value to produce revenue is a losing investment. Period. I know enough writers to safely say that most of us would see the value of a platform of this nature, not in the quick buck, which won't last, hell a new author probably signs on at least every hour, so maintaining any kind of audience in a platform like that is risky at best. So, if I put two decent quality pieces there every day, I'm looking at needing to derive half of my income from immediate payouts on Steemit, or adding 2-5 hours to every work day to accommodate it. 
There are other benefits,to be sure. Immediate recognition is good. The conversational nature of the platform is good. It is helping me redevelop some good habits to appeal to a more general audience. Last, but not least is one that is a going to quickly drop off, and that is the lack of competition makes readers more likely. But, if I am not building a reputation on a platform that will eventually develop a taste for  more sophisticated material that takes time to develop an audience, my time is better spent elsewhere. As I have already said on my steem blog, I can sell work in many other places for a few guaranteed dollars. That's a losing proposition too, as there are only so many hours in a day, no matter how prolific you train yourself to be.

**Comment by Markrmorrisjr** [comment] 2016-08-18 11:49
And, while I truly do not expect anyone to cater to me (I was writing before I found Steemit, and will have other opportunities beyond and beside it) it seems they would cut off their nose to spite their face to muzzle the ox in the middle of a drive to develop  the platform. Yes, new users are important. Yes, fresh content draws eyeballs, but lest we forget, we are competing in a global market where attention is the primary commodity. Sites like Facebook are what they are in large part due to the huge volume of content that creates a sort of gravitational pull, that ensures that most relevant content (along with a  lot of crap) will eventually be pulled into its orbit and end up on its pages. 

Even with all of the tweaking of the Google algorithms, content is still king and the more relevant and evergreen it is, the more likely it will rise and stay at the top. So, while there are better minds than me at developing block chain and understanding crypto, I know how to take a blog from zero and make it have a thousand readers at the end of a month, with nothing but social media shares that are automated. You know what it takes? Relevant, keyword tuned content that is easy to find and targeted at an intelligent audience with a taste for more. That is not what they will be developing with this model. Their content will not be building the kind of magnetism that makes Steemit a long lived powerhouse in social media. Which it could be.

**Comment by theoreticalbts** [comment] 2016-08-18 17:46
There are too many large, interconnected and nebulous issues to be discussed in a single ticket. So we should move the discussion to steemit.com -- I've started things off with [this post](https://steemit.com/theoretical/@theoretical/improving-the-steem-platform-for-long-term-content).

The two big questions are:

- Should Type II content (i.e. content with long-term relevance) be a first-class citizen in Steem?
- If so, what is the right path to making Type II content a first-class citizen in Steem?

I don't have a clear answer to either of these questions in my own mind, let alone anything resembling a consensus of the development team or the community. These issues are simply too big to be addressed in a single ticket.

**Comment by theoreticalbts** [comment] 2016-08-18 17:52
Getting back to practical matters -- namely, whether to revert to the previous behavior or keep the current behavior -- I am going to say that in the interest of minimizing the amount of work and hardforking changes required, we'll keep the current implementation as-is, and keep discussions off the bug tracker, until we have a better idea of how we're going to address this.

I'm closing this ticket because the question is simply too large, nebulous, and philosophical to be appropriate to a bug tracker, until we have a clearer philosophy of the place of long-term content in the Steem ecosystem, and a practical implementation strategy which prescribes (at least broad outlines of) specific changes and features.

**Closed by theoreticalbts** 2016-08-18 17:52 UTC

**Comment by Alifton** [comment] 2016-08-18 18:06
@theoreticalbts Agreed this debate ran way beyond the scope of a Github issue ticket and would better be relegated back onto the Steemit platform for reasons of visibility, discussion and reduction of clutter on Github.  I had already begun a wall of text again before I had to take a step back and realized this isn't the place for a debate.

This is Github after all, and it's meant to be used for code related issues.  It's not a platform designed to be an open forum for debating non code related issues.  Good call @theoreticalbts on closing this issue and pushing it back on to Steemit.  It's rough sometimes when everyone has a strong opinion regarding an issue but them's the breaks, especially during a beta of this magnitude.  ;-)

**Comment by Markrmorrisjr** [comment] 2016-08-18 18:35
I apologize, for not understanding the github etiquette.

**Comment by liondani** [comment] 2016-08-23 22:43
@theoreticalbts 
> The reason for the 30-day window is to allow old posts to be archived -- get them out of the database. Our memory usage is already getting uncomfortably large; requiring everyone to keep everything back to the beginning of time will be counterproductive.

Could we put the posts older than 30 days on a "sleep mode" that get waked up from the blockchain only if they expand their value more than 10% for example? How many post would fulfill a criteria like this(or similar)? I guess only a minority would "wake up" and restored to the database (aka RAM) so not so counterproductive as was the first impression...

**Comment by iamsmooth** [comment] 2016-08-25 06:43
@liondani 
> Could we put the posts older than 30 days on a "sleep mode" that get "waked up" from the blockchain only if they expand their value more than 10% for example?

This is exactly the sort of large and long term issue that @theoreticalbts correctly stated is not appropriate for a bug tracker. It doesn't mean these issues shouldn't be discussed, and maybe even on steemit itself is not the right place (is twitter the right place for such discussions?). But now I'm getting into issues in appropriate for a bug tracker as well, so I will sign off.

**Comment by liondani** [comment] 2016-09-03 15:08
@iamsmooth 

It seems @xeroc found a elegant solution to this....
https://github.com/steemit/steem/issues/339
