### ISSUE TITLE
Supply checks should support SMT's

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1515] opened 2017-09-06 15:42 UTC
The supply accounting should support SMT's.

In more detail:

- There is a method called `database::validate_invariants()` which ensures the sum of tokens in all places where they can exist [1] is equal to the total supply [2].

- Implement `validate_smt_invariants(db)` which does similar checks for SMT's.

The reason for this functionality is to help ensure that we have no bugs that can create / destroy SMT's in the wrong places.  Any code path that intentionally creates / destroys SMT's should be routed through `adjust_supply()` which modifies the supply field of the SMT object.  Unit tests using the `database_fixture` should always run `validate_invariants()` and `validate_smt_invariants()` after the test.

[1] "Places where tokens can exist" includes user balances, market orders, `total_vesting`, escrow, savings, reward balances, etc.

[2] The total supply is tracked in GPO fields `current_supply` (for STEEM) and `current_sbd_supply` (for SBD).  For SMT's, each SMT should have its own supply field on the SMT object.

**Comment by theoreticalbts** [comment] 2017-11-27 22:46
Added some detail to OP.  @youkaicountry this is not strictly necessary for MVP, but we should do it sooner rather than later so bugs are caught ASAP (this is mostly useful during the initial development phase, if bugs of this kind are going to happen, they will probably happen near the beginning of the project).

**Comment by youkaicountry** [comment] 2017-11-27 22:52
@theoreticalbts This appears to be a duplicate of #1648

**Comment by theoreticalbts** [comment] 2017-11-27 22:57
Unassigned myself since I'm not actively working on this at the moment.

**Comment by Kiwonik** [comment] 2017-12-15 14:37
Partially implemented. Further implementation awaits merging of pending PRs (e.g. PR 1872).

**Comment by youkaicountry** [comment] 2018-01-08 15:23
#1872 is now merged.

**Comment by Kiwonik** [comment] 2018-01-12 13:08
Expanded SMT supply control over market orders. Further expansions require that SMT vesting and rewards are implemented.

**Comment by Kiwonik** [comment] 2018-01-16 11:33
Reopening due to not being complete, see my previous comment above.

**Comment by youkaicountry** [comment] 2018-08-14 22:45
Closing as outdated.

**Closed by youkaicountry** 2018-08-14 22:45 UTC
Labels: project/smt_v05
