### ISSUE TITLE
Reuse Feed Objects

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1948] opened 2017-12-27 15:26 UTC
> Reuse feed objects in the follow-plugin data model instead of removing them and creating new one

I do not know which branch this is implemented in, but it is marked complete in #1923

Let's get this in its own branch and make a PR for it.

**Comment by mariusztrela** [comment] 2018-01-15 15:26
This issue is duplicate of #1947

**Closed by mariusztrela** 2018-01-15 15:26 UTC
