### ISSUE TITLE
Enhancement: Fix the transfer command so people can transfer 100 STEEM and not have to type 100.000 STEEM

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#73] opened 2016-06-01 12:58 UTC
If someone does not know this they can't transfer funds.

**Comment by mvandeberg** [comment] 2016-06-01 13:18
There is an example of how to use the command in the cli wallet, displaying the precision.

It is possible we could do an increase of the precision. The issue is that "100 STEEM" and "100.000 STEEM" have different binary representations and so they serialize differently. I have only heard a complaint or two. It is an idiosyncrasy of our wallet, but I am not under the impression it is a blocking issue for users.

**Comment by theoreticalbts** [comment] 2016-08-16 21:05
I'm going to close this, I don't think anyone cares enough to fix it.

**Closed by theoreticalbts** 2016-08-16 21:05 UTC
