### ISSUE TITLE
segfault when broadcasting a transaction

### ISSUE THREAD

**Issue by wackou** [steemit/steem#36] opened 2016-04-28 14:29 UTC
when broadcasting a transaction in OSX, the client invariably segfaults after having broadcasted it.

It happens because in here: https://github.com/steemit/steem/blob/master/libraries/app/api.cpp#L98 we have `capture_this == nullptr`.

After a quick analysis (I might be wrong but I think this is the issue), I believe this was introduced with this commit: https://github.com/steemit/steem/commit/74e2412c1364c37b3b570747e4fee6a38b2ac55f

The problem comes from the fact that `shared_from_this()` only works reliably when there already exists a shared_ptr from the class it is called, which was the case before, however after 74e2412 the explicit `shared_ptr<network_broadcast_api>`, etc. that were created upon login have been replaced with `fc::api_ptr` which is a generic pointer and breaks the promise of having a `shared_ptr` before (ie: the `weak_ptr` in `std::enable_shared_from_this` has not been initialized yet, see: http://en.cppreference.com/w/cpp/memory/enable_shared_from_this).

I have a hunch that the following issues might also be related to this: #10, #11, #26

**Comment by bytemaster** [comment] 2016-04-28 15:16
Can we get confirmation that those other issues #10 #11, and #26 occurred after broadcasting a transaction and then disconnecting before confirmation?

**Comment by theoreticalbts** [comment] 2016-04-28 16:28
Reopening because this issue may exist if other API's provide callbacks, we'll need to review each one.  Also there should be a way in the framework, so creating an API which provides a callback involves a minimum amount of boilerplate.

**Comment by theoreticalbts** [comment] 2016-04-28 16:39
I think it may be a race, the signal handler should be deregistered when the `_applied_block_connection` object is deleted in the API object's destructor.  So usually you'd avoid calling with invalid `this`, because the thing which causes the calls (existing as a signal handler) stops happening around the time `this` becomes invalid (which happens because `this` was destroyed, which would have caused the signal handler to be deregistered when the connection member object was destroyed).

But if the signal handler execution's already started, it can't be cancelled in flight, leading to problems if it expects `this` to be valid for the duration of the call.  So @bytemaster's patch looks like the correct solution -- using a `weak_ptr` which you `lock()` and then test the result instead of using `this` as a raw pointer.

**Comment by wackou** [comment] 2016-04-28 18:54
it still crashes... However, it looks like some progress has been made. When entering on_applied_block, capture_this is now valid, but it crashes a bit later while instantiating the async task and copying (?) the lambda. I have to admit that at this point, what is actually happening eludes me, so here are some screenshots of the debugger (sorry for the small size, I'm travelling and only have my laptop)

frame 5, up till here all good
![frame_5](https://cloud.githubusercontent.com/assets/15667/14897407/2fe6e23a-0d82-11e6-901b-72293296629b.png)
frame 4, 3, 2: creating the async task
![frame_4](https://cloud.githubusercontent.com/assets/15667/14897406/2fe6a54a-0d82-11e6-8353-439ce0270470.png)

![frame_3](https://cloud.githubusercontent.com/assets/15667/14897410/2fea95c4-0d82-11e6-964f-fb9ebb71e1db.png)

![frame_2](https://cloud.githubusercontent.com/assets/15667/14897409/2fe91ae6-0d82-11e6-8717-cfb2781c03ff.png)

frame 1: for some reason here inside the lambda, `capture_this` is null again... btw, if we have `capture_this`, is it necessary to also capture `this` in the declaration of the lambda?

![frame_1](https://cloud.githubusercontent.com/assets/15667/14897408/2fe7397e-0d82-11e6-9164-9c3be354b0da.png)

let me know if I can do anything else to help

**Comment by bytemaster** [comment] 2016-04-28 19:57
I think it might have something to do with the iterator containing the lambda being erased. I opted for a slow memory leak rather than a crash.  See if the latest commits fix it.  If so then we can dig deeper.

**Comment by theoreticalbts** [comment] 2016-04-28 20:00
In refactoring the original patch I found that `database_api` suffers from the same bug.  Just pushed 993689291caae5be9718134decc69004feb2338e to develop which should fix `database_api` at least.

**Comment by wackou** [comment] 2016-04-28 21:25
still crashes in the same place...

**Comment by roadscape** [comment] 2016-05-01 00:45
> Can we get confirmation that those other issues #10 #11, and #26 occurred after broadcasting a transaction and then disconnecting before confirmation?

None of those issues are related to broadcasting a transaction --- the node on which those occur only serves as an RPC API, and the only calls I make are reading the state.

**Comment by wackou** [comment] 2016-05-16 20:31
I was wondering whether it was a problem with the OS or the compiler/libc++, so I tried compiling on linux using clang as compiler to see whether it would crash (debian jessie, clang-3.5, boost 1.58.0). It turns out that it works perfectly there. So it would seem that the issue is either OSX-specific or comes from a difference between clang/libc++ 3.5.0 on linux and clang/libc++ (Apple LLVM version 7.3.0) on OSX.

**Comment by svk31** [comment] 2016-08-08 17:04
Bumping since this is still an issue for me, and a quite annoying one since it makes it impossible to use either the cli_wallet or a local websocket connection when developing for steemit.com. As soon as I make a transaction of any kind, steemd segfaults and I then need to do a full replay.

![image](https://cloud.githubusercontent.com/assets/6890015/17488502/fb4da0b4-5d99-11e6-91b9-15af05cb525b.png)

```
Boost version: 1.60.0
OPENSSL_VERSION = 1.0.2h
```

**Comment by wackou** [comment] 2016-08-15 21:29
I put a bounty of 400 STEEM on this bug, if anyone is interested... (I can also pay 800 SD, which is what 400 STEEM was worth at the time the bounty was set). See https://steemit.com/steem/@wackou/btstools-development-bounties

**Comment by theoreticalbts** [comment] 2016-08-17 14:57
This is likely duplicate of #281.  I've identified the root cause and a patch will be pushed soon.

**Comment by sneak** [comment] 2016-10-04 23:20
@theoreticalbts could you please verify that #281 fixes this and close if so?

**Comment by wackou** [comment] 2016-10-05 09:10
v0.14.2 still exhibits this issue...

**Comment by svk31** [comment] 2016-10-05 09:19
I just compiled and synced from the develop branch and it also still exhibits this issue. Definitely not fixed.

**Comment by theoreticalbts** [comment] 2016-10-05 14:50
@sneak I cannot verify that this is fixed because I cannot reproduce it.  It only seems to happen on some machines, and it has never happened on any machine I have used.

**Comment by theoreticalbts** [comment] 2016-10-05 18:44
The network_broadcast API will be deprecated and replaced by a stateless network_broadcast2 API, as discussed in #490.  Closing this ticket as wontfix.

**Comment by bytemaster** [comment] 2016-11-22 16:03
For backward compatibility and to facilitate smooth transition to new stateless API we still need to fix this.

**Closed** 2016-11-22 16:06 UTC
Labels: bug, status/WIP, wontfix
