### ISSUE TITLE
Could not find API account_history_api : account_history_api.get_account_history 

### ISSUE THREAD

**Issue by muksihs** [steemit/steem#3072] opened 2018-10-16 00:15 UTC
Attempting to call "account_history_api.get_account_history" results in api endpoint not found error.
```json
echo;echo;curl -s --data '{"jsonrpc":"2.0", "method":"account_history_api.get_account_history", "params":{"account":"leatherdog-games", "start":-1, "limit":1}, "id":1}' https://api.steemit.com; echo; echo
```
```json
{"jsonrpc":"2.0","error":{"code":-32002,"message":"Assert Exception:api_itr != _registered_apis.end(): Could not find API account_history_api","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"json_rpc_plugin.cpp","line":206,"method":"find_api_method","hostname":"","timestamp":"2018-10-16T00:13:31"},"format":"api_itr != _registered_apis.end(): Could not find API ${api}","data":{"api":"account_history_api"}}]}},"id":1}
```

**Comment by mvandeberg** [comment] 2018-10-16 00:18
Duplicate of steemit/jussi#212

**Closed by mvandeberg** 2018-10-16 00:18 UTC
