### ISSUE TITLE
Digging into JSON metadata through SteemSQL for a double post follow bug

### ISSUE THREAD

**Issue by jasonbutt** [steemit/steem#1861] opened 2017-12-08 07:45 UTC
# Querying and Validating JSON in SQL

I was looking for a way to determine how many times I might have followed someone or if a follow was recorded more than once, or perhaps not at all in the blockchain.  I was looking at this as corroboration on a bug that I had found.

I had looked at several potential methods at exploring the information but ended up going through MSSMS and into the SteemSQL database to explore. 

## Background
I found that the information that I was looking for is in the TXCustoms table.  This is the table that contains the following fields: 

**tx_id**, **tid**, **json_metadata**, **timestamp**.

The **json_metadata** is the field that we are interested in searching through. It appears as there is two type of JSON data in the json_metadata column,  follow[Unfollow][Mute] and reblog. 

- **Follow** - ```["follow",{"follower":"jasonbu","following":"fabien","what":["blog"]}]```
- **Unfollow** -``` ["follow",{"follower":"jasonbu","following":"fabien","what":[]}]```
- **Mute** - ```["follow",{"follower":"jasonbu","following":"geke","what":["ignore"]}]```
and
-  **Resteem** -```["reblog",{"account":"argd88","author":"sancho.panza","permlink":"concurso-recital-de-poesia-sancho-panza"}]```

## Querying the Data
Querying the table is pretty straightforward, until you want to isolate your WHERE clause to data points within the JSON text. For instance, I wanted to find out how many times I had followed the user Gmuxx.

Here's what one of the strings from the JSON_metadata column looks like 

```["follow",{"follower":"jasonbu","following":"pocket-pi","what":["blog"]}]```

That's a bit messy, but you can clearly see the elements of the JSON records.  Let's have a look at it broken out. Notice the 1 and the 0. Those are key to getting at the data elements in the string.
<center>![Imgur](https://i.imgur.com/mZiXMw5.png)</center>

Luckily SQL has a few built-in functions for dealing with JSON strings.
>If you have JSON text that's stored in database tables, you can use built-in functions to read or modify values in the JSON text. +
>- Use the **JSON_VALUE** function to extract a scalar value from a JSON string.
>- Use **JSON_QUERY** to extract an object or an array from a JSON string.
>- Use the **ISJSON** function to test whether a string contains valid JSON.
>- Use the **JSON_MODIFY** function to change a value in a JSON string.
<sub>Source: [Doc.Microsoft.com](https://docs.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server#combine-relational-and-json-data)</sub>

We will use the **ISJSON** and **JSON_VALUE** functions to query the** json_metadata** field.  Recall the 1 and the 0 from the image above.  

We will use the $[0] to specify the first element in the string 

<center>![Imgur](https://i.imgur.com/jIOa9ux.png)</center>

and then the $[1] to reference the second element in the string. To get at the "follower" data element we would reference it using $[1].follower and if we want the "following" data with $[1].following. 

<center>![Imgur](https://i.imgur.com/vHuVNyf.png)</center>

## The Query
My initial query checked that the field contained JSON data. It then checked for the "follow" type and then specifically for the "follower" being me and after the date that I joined Steemit. 

<center>![Imgur](https://i.imgur.com/sLxmo5R.png)</center>

** Remember to use **NOLOCK**

That returned all the records for when I followed someone on the platform. If you recall I wanted to know how many times I had voted for Gmuxx, specifically. I modified the query to include $[1].following and was rewarded with the following results. 

<center>![Imgur]([Imgur](https://i.imgur.com/cLRqg5F.png))</center>

As you can see I did actually follow Gmuxx twice. The data is confirmation of the bug. 

Hope you found this helpful and let me know if you have any questions. 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@jasonbu/digging-into-json-metadata-through-steemsql">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mvandeberg** [comment] 2017-12-08 15:34
While this is interesting, it has nothing to do with the development of the Steem blockchain. Closing this as off topic.

**Comment by theoreticalbts** [comment] 2017-12-08 15:47
@mvandeberg, you need to read this more closely.  This is actually a bug report showing a double follow that got into the blockchain.  Although it is probably not a bug in `steemd`, this may indicate a bug in the follow plugin.

@jasonbutt, good work digging into this stuff.  I'm glad to see the community is producing tooling like this.

Once the blockchain sees a `custom_json_operation`, all it checks is that the contents is valid UTF-8 JSON.  It doesn't do any further validation [1].  Anyone can put any JSON they want in there, and it will go into the blockchain.

So what's needed to implement following is some code that "walks" the blockchain block-by-block and maintains a list of "who's following whom."  The walker has to be able to deal with "illegal" state -- what if required fields are left out (for example a `"following"` field but no `"follower"`, a list where a string is expected, etc.), what if someone follows an account that does not exist (keep in mind you have to also have a list of accounts that existed *at that block*), what if someone follows an account twice (without an unfollow in between), what if the required signatures don't match, etc.

For follows, the walker is currently implemented in an *optional* C++ plugin for `steemd` called `follow_plugin`.  It's optional, so nodes that don't run this plugin have no way of detecting double follows -- they literally aren't running any code that lets them understand what following means.  For various reasons, this C++ plugin is in the process of being deprecated, for steemit.com it will soon be replaced by a completely external Python application called `hivemind`.  Witnesses are encouraged to minimize the plugins they run for security, stability and resource efficiency, so the core network doesn't have any way to reject double follows.

So back to the topic of this ticket.  If the UI you are using submits its transactions to a node running `follow_plugin`, then this ticket is actually a bug that belongs in this repo -- `follow_plugin` should check locally submitted transactions don't double follow.

So how did you do the double follow?  What UI are you using?  You've shown the steps to see a double follow occurred, can you make one occur on command?

[1]  If the blockchain did any further validation, then if you want to use `custom_json_operation` for anything, you'd have to implement your operation in C++ in `steemd` and convince the witnesses to do a hardfork upgrade to your version of it.  This is a pretty high bar.

**Comment by mvandeberg** [comment] 2017-12-08 16:06
When evaluating a custom json operation, if the plugin throws an exception, the operation will be rejected if the node is producing a block or applying a new transaction to their mempool (outside of block production).

This is a relatively small fix to check that `old_what != new_what`. Preventing the operation entering the blockchain is dependent on what plugins are loaded on the steemd node the API uses or the witnesses. The witnesses are recommended to not run the follow plugin so it is completely dependent on the API node.

However, many parts of the follow plugin (including tracking follows) are being moved to an external service called hivemind and will no longer live in steemd. Soon there will not be a way for this operation to be rejected at all in a steemd node (as described above). I am labelling as `WON'T FIX` because it is an upgrade to soon to be deprecated code.

**Closed by mvandeberg** 2017-12-08 16:06 UTC
Labels: wontfix
