### ISSUE TITLE
Keep votes around indefinitely

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#337] opened 2016-08-31 16:59 UTC
Do you think it is a good idea to leave active_votes populated indefinitely?  It looks like that is the only change needed to fix the UI.

https://github.com/steemit/steemit.com/issues/188
vote count beyond 30 days always shows 0 · steemit/steemit.com · GitHub

>After a posts 30-day payout, the active_votes array is returned from the API empty. This causes posts past 30 days to lose their vote counts.
 

vandeberg [1:47 PM]  
Keeping votes around indefinitely needs to be done as a plugin.
Removing them from consensus allows us to slow memory growth.

**Comment by mvandeberg** [comment] 2016-09-01 12:11
There is a build option CLEAR_VOTES that clears votes from consensus that is on by default.

`-DCLEAR_VOTES=OFF` will keep them around. Not sure if it stores new votes after an archived post though... Will check on that.

Ultimately, this will be moved to a plugin rather than a build option, but it was an easy workaround.

We also need to decide if default build parameters and plugins are going to reflect what we need for steemit.com nodes or what witnesses should be running for a consensus node. My opinion is that it should be the consensus only configuration and our steemit.com build/deploy scripts should handle setting up the correct configuration.

**Comment by iamsmooth** [comment] 2016-09-02 15:22
@mvandeberg please document the steemit build and deployment configuration because there has already been some confusion when people are using different plugins and see different results. Build options changing behavior add another level of complexity to it.

**Comment by mvandeberg** [comment] 2016-09-02 16:44
Build options are documented in README.md

**Comment by Gandalf-the-Grey** [comment] 2016-09-17 08:17
Confirmed and fixed already `-DCLEAR_VOTES=OFF` [fixes issue on UI ](https://github.com/steemit/steemit.com/issues/188)
(There was wrong assumption of its default value)

**Comment by theoreticalbts** [comment] 2016-09-30 19:05
Closing this ticket because it seems there's an option for this behavior, and according the last comment above, the UI has what it needs.

**Closed by theoreticalbts** 2016-09-30 19:05 UTC
