### ISSUE TITLE
Compiled code is compatible with windows

### ISSUE THREAD

**Issue by xiangxn** [steemit/steem#311] opened 2016-08-21 13:33 UTC
Compiled code is compatible with windows Visual Studio 2013:
witness.cpp[409]:
old:`void witness_plugin::on_applied_block( const chain::signed_block& b )`
**new:`void witness_plugin::on_applied_block(const steemit::chain::signed_block& b)`**

market_history_plugin.cpp[24]:
old:`flat_set<uint32_t>     _tracked_buckets = { 15, 60, 300, 3600, 86400 };`
**new:`flat_set<uint32_t>     _tracked_buckets = flat_set<uint32_t>{ 15, 60, 300, 3600, 86400 };`**

authority.cpp[82]:
old:
```for( auto item : account_auths )
      FC_ASSERT( is_valid_account_name( item.first ) );```
**new:
```for (auto item : account_auths){
		FC_ASSERT(is_valid_account_name(item.first));
	}```**

database.cpp[2013]:
old:`if( shares == 0 ) return;`
**new:`if (shares == fc::uint128(0)) return;`**
The above modification in vs2013 compile "steemd.exe"

**Comment by abitmore** [comment] 2016-08-23 00:56
Better submit a pull request.

**Comment by theoreticalbts** [comment] 2016-08-26 17:13
Duplicate of #288 -- these issues were reported by @btscube in [prehistoric times](https://github.com/steemit/steem/pull/138), and have been merged to develop for a while.

**Closed by theoreticalbts** 2016-08-26 17:13 UTC

**Comment by xiangxn** [comment] 2016-08-28 04:07
merged?
The combined not master?

**Comment by xiangxn** [comment] 2016-08-28 04:11
There is also a small bug: division by zero
