### ISSUE TITLE
`sbd_print_rate` is 1% in the haircut

### ISSUE THREAD

**Issue by joticajulian** [steemit/steem#3409] opened 2019-07-19 10:36 UTC
When the haircut price applies, the virtual supply is:
`virtual_supply = current_supply + current_supply/9`

What is the `sbd_print_rate`?
https://github.com/steemit/steem/blob/a470bc283260e582b56897bd5c68107aa0289f18/libraries/chain/database.cpp#L3901-L3909

```percent_sbd = ( current_supply/9 * 10000 ) / ( current_supply + current_supply/9 )```

The problem with this formula is that all operations are made with integers. Meaning that the **percent_sbd will be 1000 only if the `current_supply` is divisible by 9. Otherwise it always be 999**.

If `percent_sbd == 999` then `sbd_print_rate=1%`.

**Comment by TimCliff** [comment] 2019-07-20 06:33
@joticajulian this is a duplicate of issue 3184 which has already been fixed/closed. 

In terms of the 5% jump that you mentioned in PR  https://github.com/steemit/steem/pull/3410, the `STEEM_SBD_STOP_ADJUST` value of `5` is not `5%`. `sbd_stop_percent` is `10 * 100 = 1000`, so `dgp.sbd_stop_percent - dgp.sbd_stop_adjust` is `995`. The `5` is a very small difference relative to the whole, and should not have a noticeable impact.

**Comment by joticajulian** [comment] 2019-07-20 07:17
Maybe 0.05% in `percent_sbd` could be seen as a small variation. But no, is very big, because `sbd_print_rate` acts like a zoom, **1% variation in `percent_sbd` (from 9% to 10%) represents 100% variation in `sbd_print_rate`!**.

Suppose that the `percent_sbd` is 9.95%, that is, 995 in the code. 

Now look this code:

`if( percent_sbd >= dgp.sbd_stop_percent - dgp.sbd_stop_adjust ) 
   dgp.sbd_print_rate = 0;`

In other words:

`if ( 995 >= 1000-5) sbd_print_rate = 0`

Which is True, then the print rate will be zero.

Now let's see the behavior in the code without `sbd_stop_adjust`:


```if( percent_sbd >= dgp.sbd_stop_percent ) 
   dgp.sbd_print_rate = 0;
else 
   dgp.sbd_print_rate = ( ( dgp.sbd_stop_percent - percent_sbd ) * STEEM_100_PERCENT ) / ( dgp.sbd_stop_percent - dgp.sbd_start_percent );
```

In other words 

```if( 995 >= 1000 ) 
   dgp.sbd_print_rate = 0;
else 
   dgp.sbd_print_rate = ( ( 1000 - 995 ) * 10000 ) / ( 1000 - 900 );
```

The first statement is false and applies the second 

`sbd_print_rate = 5 * 10000 / 100 = 500`

500, that is 5%. Do you see the difference?

**Comment by joticajulian** [comment] 2019-07-20 07:26
And yes. It is duplicated, sorry. I found that issue after publishing this. Then, I wanted to close it but when I saw the fix I found this new problem.

**Comment by TimCliff** [comment] 2019-07-21 05:05
I see.. You are correct.

I don't think the impact is significant enough though to warrant a code change. The case where the debt ratio is within .05% of the 10% limit is a very rare occurrence, and even when it does happen - it usually does not stay in that range for an extended period of time. If it is that close, minor changes in STEEM price are going to be enough to push it in one direction or another.

The more important thing (which the existing code change addresses) is that once it is _past_ the 10% limit, that it should stay at a print rate of zero.

**Comment by eonwarped** [comment] 2019-07-21 16:22
To add to this, you need to make doubly-sure your code is not affecting
computations pre-fork. When I looked at the code just now it seemed like it
might, but I wasn't sure.

**Closed** 2019-07-24 17:04 UTC
