### ISSUE TITLE
SIP - Witness Police of Abusive Voting

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#323] opened 2016-08-25 19:48 UTC
After the discussion on negative voting resulted in rejection from users, we were left with the problem of dealing with abusive voters.  These are hacked accounts or whales that vote in a manner that is clearly contrary to the platform and which require pro-active policing by other whales.

Some people have identified an attack vector discussed in #316 (self rewarding bot) which becomes a bigger problem as posts get bigger.   

Any user who the "collective" finds to be annoying enough that they need to run bots to counteract their behavior is a user whose curation votes should be neutralized.  

If the top 19 active witnesses have a majority vote in favor of banning another user's curation privileges then that user will no longer be permitted to vote on content.

This has the property that all witnesses are subject to whale support to keep their position and if a group of witnesses start abusing this power they will be voted out.  This power does not negate an accounts ability to vote on witnesses. 

Overall this would allow the network to heal / reject an abusive user while raising the bar high enough that it will not be used frivolously.

**Comment by arhag** [comment] 2016-08-26 22:54
Still on the fence about this, but if it is to be implemented it should also be possible for the same quorum of witnesses to remove the curation restriction. Also, a restriction on curation privileges of course shouldn't take away their right use a future non-consensus voting mechanism (which doesn't change regards or user voting power) to express their opinions on posts/comments (this is a feature needed anyway to allow regular users to vote or update their vote after a discussion had been archived).

Finally, I'm thinking perhaps the curation restriction should have some time limit (e.g. 6 months) before it will automatically be removed unless it was renewed by the witnesses with another majority vote.

**Comment by matthewniemerg** [comment] 2016-08-31 16:12
Can you define majority?  Simple majority (i.e. 10) or are we looking at supermajority (66% or greater, i.e. 13+).

**Comment by nextgencrypto** [comment] 2016-08-31 16:22
This is nothing but ANOTHER method for Dan and his controlled witness list to take control over peoples voting abilities based on his ASSUMPTION that people don't agree with the voting that is taking place on the platform.

Once again, censorship at its finest.

**Comment by R4FKEN** [comment] 2016-08-31 16:32
No, this is a way to remove censoring dictators like @anyx who ban random innocent users like me with their SP. They should get kicked in the gonads after being stripped of their witness power.

**Comment by R4FKEN** [comment] 2016-08-31 16:34
@cryptosomething YOU are giving ONE user the power to play God, not even 19

**Comment by R4FKEN** [comment] 2016-08-31 16:42
https://steemit.com/spam/@nextgencrypto/a-message-to-spam-bot-jillstein2016
And you've extended your "mission" to downvote anyone that your master @anyx decides seemingly random. 'Nuff said.

**Comment by R4FKEN** [comment] 2016-08-31 17:18
While we're at it, see https://steemit.com/steemit/@r4fken/daily-downvote-from-gestapo-kommandant-anyx-and-his-army-of-ss-bots

Plenty of upvotes, right? Takes only 1 (here 2) dipshits with SP who downvote

**Comment by Riverhead** [comment] 2016-08-31 17:28
I'd like to see how Steemcleaners, a community project, makes out before something like this gets baked into the product.

**Comment by R4FKEN** [comment] 2016-08-31 18:23
Now I realise. I know who berniesanders is! You really ARE the born rich spoiled kid that always wants it his way. Good for you!

**Comment by bacchist** [comment] 2016-08-31 18:30
I was under the impression that voting is the appropriate method of accomplishing this. I can only interpret this as a further attempt to gain extra privileges and control, beyond the already massive disparity in power.

**Comment by steemed** [comment] 2016-08-31 21:27
@R4FKEN

The last thing the witness slots under Dan's control are going to do is ban @anyx. And @berniesanders is not necessarily your enemy for cooperating with @anyx _sometimes_.

Centralizing maneuvers like this proposal undermine the natural competition that enforces fairness in markets, here the voting power market.

Your hope as a little guy doesn't come from protection by big brother Dan and his gang. It comes from the fact that players have competing interests from time to time, so cooperation is tenuous and always contingent on mutual benefit.

You will lose more of whatever hope you have if collusion is enshrined as it would be in this proposal.

**Comment by anyx** [comment] 2016-08-31 21:30
Please, stop mention me. This is some mistake.
Thanks

**Comment by Any-x** [comment] 2016-09-01 04:22
Sorry other anyx, I am the anyx they are referring to. Take care with the @ mentions on github! :)

First, r4fken (or do you prefer being called caitlinm?), you are not being censored, all your messages are visible on the blockchain and even on the site. Second, cheetah bans are in no way official bans, the community can decide for themselves.
Third, if anyone is curious why r4fken is on my black list, it is because his alt account (caitlinm) was caught for ID theft and defrauding Steemit using fiver. He admitted this to me in a PM in chat, in between telling me he has other alt accounts (likely also scamming) and calling me Hitler.
If anyone would like to follow up on the evidence feel free to contact me on chat and we can go over it.

Anyways, apologies to everyone for going off topic on this github issue, but this was out of hand and I felt like I needed to respond.

**Comment by R4FKEN** [comment] 2016-09-01 04:58
Caitlinm is fiction, just like berniesanders is. You're leaving him alone tho, I wonder why...

**Comment by R4FKEN** [comment] 2016-09-01 05:12
And please tell me whose identity I have stolen. You and your disciples keep mentioning identity theft without knowing what it really means. You should talk to a victim of actual ID theft, learn about the actual crime that you're accusing everyone of.
In fact, caitlinm is a fictional name, while berniesanders is obviously an existing person. Who's the thief?

**Comment by Riverhead** [comment] 2016-09-01 11:35
Given the above I'd guess @Any-x  means IP theft, not ID. That said, and given the support and also backlash of people using their massive accounts to enforce a type of censorship or shaming, indicates the community is not yet comfortable with such mechanisms as would be implemented in SIP #323.

Lastly, can we please keep in mind that these are proposals put up for discussion. Let's keep the ad hominem in check, eh?

**Comment by R4FKEN** [comment] 2016-09-01 11:40
IP theft, I assume you mean copyright infringement? Which is *reproducing, distributing, displaying or performing a work, or to make derivative works, without permission from the copyright holder*.
I have permission in all cases this could be applicable.

**Comment by mvandeberg** [comment] 2016-09-01 12:26
@bacchist 

> I was under the impression that voting is the appropriate method of accomplishing this. I can only interpret this as a further attempt to gain extra privileges and control, beyond the already massive disparity in power.

Voting does a good job of vetting content, but not vetting curation. Let's say a minnow makes a blog post. It is getting some upvotes (maybe to $5) and a whale comes along and bumps it to $200. You, also being a whale, like the post but do not believe it is worth $200. Maybe it is worth $50. You have two options.

1. Downvote the post to $50.
2. Upvote everything else to dilute rshares so the post only gets $50.

Option 1 is the easiest. But let's say you downvote, the other whale removes your vote, and them points out that you silenced and innocent minnow. Now you look like the bad guy. Maybe you are for downvoting a minnow in the first place, but you look a lot worse than you actually are. Sure, the evidence of what happened is on the blockchain, but most users won't go through the hassle of looking that up. 

Option 2 is unreasonably demanding, especially if you are low on voting power.

This proposal is designed to remove user voting power if a majority of witnesses believe that the value of the platform would increase as a result of this user being unable to vote. Do note, this would only silence their ability to vote on content, not witnesses. If a new regime came into power that thought the whale would provide value, they can remove the silence. There should be enough differing opinions across 19 witnesses as to what provides value such that it is difficult to convince a majority of the same value judgment.

**Comment by iamsmooth** [comment] 2016-09-25 07:22
First of all this is a fairly extreme measure and if implemented should be more than a simple majority of witnesses. In cases of clear and unambiguous abuse (such as rampant malicious downvoting with no clear expressive or constructive purpose), it should be possible to get near-unanimity of not actual unanimity of elected witnesses. 

Second of all, in response to @mvandeberg's reply to @bacchist, frankly I'm not convinced by the existence of fairly contrived edge cases in voting where such-and-such happens on a particular post in a such-and-such sequence that this justifies such a radical change and an increase the degree of major stakeholder control over other participants in a system that is already frequently and widely challenged for its degree of centralization. In no way is it clear that overall the proposed solution is preferable to the stated problem.

Finally, the example given points to a deeper problem with the very concept of "changing votes", because voting in Steem is sequential in nature and such changes to earlier votes retroactively alter the meaning of any subsequent votes in a manner that is difficult if not impossible to anticipate at the time those subsequent votes were made. Perhaps a more comprehensive rethink of vote changing is called for.

**Comment by mvandeberg** [comment] 2018-07-27 00:21
Closing due to age.

**Closed by mvandeberg** 2018-07-27 00:21 UTC
