### ISSUE TITLE
Failure to build 0.20.11

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/steem#3363] opened 2019-06-20 04:48 UTC
-DLOW_MEMORY_NODE=ON -DCLEAR_VOTES=ON -DSKIP_BY_TX_ID=ON

```
[ 74%] Linking CXX executable all_tests
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `fork_once_func':
(.text+0x16): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
libraries/fc/tests/CMakeFiles/all_tests.dir/build.make:532: recipe for target 'libraries/fc/tests/all_tests' failed
make[2]: *** [libraries/fc/tests/all_tests] Error 1
make[1]: *** [libraries/fc/tests/CMakeFiles/all_tests.dir/all] Error 2
CMakeFiles/Makefile2:423: recipe for target 'libraries/fc/tests/CMakeFiles/all_tests.dir/all' failed
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sgerbino** [comment] 2019-06-20 06:56
Resolved by #3353.
Duplicate of #3352.

**Comment by Jolly-Pirate** [comment] 2019-06-20 13:25
I was building with tag v0.20.11. Master is now HF21 and won't run with HF20. We need to be able to still build HF20.

**Comment by mvandeberg** [comment] 2019-06-20 14:18
This error was not triggered by a change in the Steem repo.

OpenSSL for Ubuntu 18.04 (perhaps others, but confirmed for 18.04) was updated from 1.1.0 to 1.1.1. It is a known build behavior of OpenSSL 1.1.1 that it must be linked prior to linking another library that requires pthreads. In the case of Steem, FC was linking to Boost prior to OpenSSL resulting in the linker error above. The fix was simply link OpenSSL prior to Boost. However, it is updating your packages that triggers this error, not a specific commit of Steem. We have fixed the linking order in `master` which will be contained in all future releases.

Below is a git patch file that will fix the linking order. We will also retag the `0.20.11` on a branch containing this fix.

```
From ca60ecb4424cf92999736099b14b374f259160e7 Mon Sep 17 00:00:00 2001
From: Michael Vandeberg <mvandeberg@users.noreply.github.com>
Date: Mon, 10 Jun 2019 15:20:38 -0700
Subject: [PATCH] Link Boost after OpenSSL #3352

---
 libraries/fc/CMakeLists.txt | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/libraries/fc/CMakeLists.txt b/libraries/fc/CMakeLists.txt
index 8b09f950..d8e33410 100644
--- a/libraries/fc/CMakeLists.txt
+++ b/libraries/fc/CMakeLists.txt
@@ -375,7 +375,7 @@ target_include_directories(fc
 IF(NOT WIN32)
   set(LINK_USR_LOCAL_LIB -L/usr/local/lib)
 ENDIF()
-target_link_libraries( fc PUBLIC ${LINK_USR_LOCAL_LIB} equihash ${Boost_LIBRARIES} ${OPENSSL_LIBRARIES} ${ZLIB_LIBRARIES} ${BZIP2_LIBRARIES} ${PLATFORM_SPECIFIC_LIBS} ${RPCRT4} ${CMAKE_DL_LIBS} ${rt_library} ${readline_libraries} ${ECC_LIB} )
+target_link_libraries( fc PUBLIC ${LINK_USR_LOCAL_LIB} equihash ${OPENSSL_LIBRARIES} ${ZLIB_LIBRARIES} ${BZIP2_LIBRARIES} ${Boost_LIBRARIES} ${PLATFORM_SPECIFIC_LIBS} ${RPCRT4} ${CMAKE_DL_LIBS} ${rt_library} ${readline_libraries} ${ECC_LIB} )
 
 if(MSVC)
   set_source_files_properties( src/network/http/websocket.cpp PROPERTIES COMPILE_FLAGS "/bigobj" )
-- 
2.17.2 (Apple Git-113)
```

**Comment by mvandeberg** [comment] 2019-06-21 17:23
The release has been retagged.

**Closed by mvandeberg** 2019-06-21 17:23 UTC

**Comment by Jolly-Pirate** [comment] 2019-06-22 17:56
Still fails to build.
```
[ 81%] Linking CXX static library libsteem_chain.a
[ 81%] Built target steem_chain
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
