### ISSUE TITLE
Updating the posting key with posting key

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#47] opened 2016-05-03 23:02 UTC
The blockchain currently prevents this, but it should be allowed.

**Comment by arhag** [comment] 2016-05-04 14:47
Is it desired behavior to allow posting authority to change the account's JSON and memo key? Because that is what this change allows.

I am not saying whether it should or shouldn't be. I guess it depends on how exactly the JSON and memo key are expected to be used. But I just want to make sure this was a conscious decision and not a bug.

**Comment by xeroc** [comment] 2016-05-04 16:15
If the posting key can change the posting key .. then you cannot let others post in your name (e.g. with your bandwidth) .. 

e.g. if wikileaks wants others to post stuff in their name, they can't just hand over the posting key to a group of people because each one of them could lock out the others.

IMHO, changing a key should require at least the active key (better yet, the owner key) </opinion>

**Comment by arhag** [comment] 2016-05-04 16:24
> IMHO, changing a key should require at least the active key (better yet, the owner key)

Definitely not the owner key! That would be very annoying.

> If the posting key can change the posting key .. then you cannot let others post in your name (e.g. with your bandwidth) ..
>
>e.g. if wikileaks wants others to post stuff in their name, they can't just hand over the posting key to a group of people because each one of them could lock out the others.

Perhaps changing posting authority should require at least active authority as it does now. But is the problem you describe really a big deal? I'm assuming the owner trusts the people in the posting authority enough for that not to be a regular problem. And if it does happen, the active authority can still change back the posting authority and remove the offender (and fire them presumably).

However, your example convinces me that if posting authority is allowed to change posting authority, then it at least shouldn't be allowed to change memo key or JSON.

**Comment by abitmore** [comment] 2016-05-04 18:09
>And if it does happen, the active authority can still change back the posting authority and remove the offender (and fire them 

Perhaps it's hard to know who did it?

**Comment by arhag** [comment] 2016-05-04 18:14
> Perhaps it's hard to know who did it?

You would have each user added individually into the posting authority (each with weight 1 and posting authority threshold would be 1). That way you have cryptographic proof of who changed what.

**Comment by xeroc** [comment] 2016-05-05 10:12
> You would have each user added individually into the posting authority (each with weight 1 and posting authority threshold would be 1). That way you have cryptographic proof of who changed what.

Right. Haven't thought about that. If I want to hand over posting control to someone else, I can still add another key to the posting authority.
But then anyone in the posting authority can remove any other posting key. With that, you remove a lot of potential uses cases in which people post in the "name of someone else" to make use of the other ones available bandwidth.

If you ask me, I don't think that the increased convenience and user experience from the OP is worth removing an entire undiscovered set of use-cases that require sharing of posting keys.

As a compromise, how about a posting key cannot change the **entire** posting authority, but only its own posting key. That way, I can share posting keys by adding more keys and let people that are in the posting authority of my account change their keys independently without affecting others that also have posting authority. This still removes some potential use-cases but is something in between.

**Comment by arhag** [comment] 2016-05-05 13:34
> As a compromise, how about a posting key cannot change the entire posting authority, but only its own posting key.

I like that solution. Other than the fact it require more significant code changes than just making it posting authority changes require at least active authority.

**Comment by theoreticalbts** [comment] 2016-08-16 19:09
I'm closing this ticket because:

- This ticket hasn't been updated in many months.
- Above discussion notes that this will preclude some desirable use cases.
- Any change to key semantics is particularly burdensome to users.
- Minimal value provided by this change, we should be spending development resources elsewhere.

**Closed by theoreticalbts** 2016-08-16 19:09 UTC
Labels: HARDFORK
