### ISSUE TITLE
confuse about a placement new

### ISSUE THREAD

**Issue by rabbitHX** [steemit/steem#2268] opened 2018-03-25 00:58 UTC
hi:
  i find a statment :  new ((char*)&_functor) FunctorType( fc::forward<Functor>(f) );
i think a placement new's type should be a struct/class/built-in type, but this seems to be a  function type, i can't understand it.
full code:

  template<typename R,uint64_t FunctorSize=64>
  class task : virtual public task_base, virtual public promise<R> {
    public:
      template<typename Functor>
      task( Functor&& f, const char* desc ):promise_base(desc), task_base(&_functor), promise<R>(desc) {
        typedef typename fc::deduce<Functor>::type FunctorType;
        static_assert( sizeof(f) <= sizeof(_functor), "sizeof(Functor) is larger than FunctorSize" );
        new ((char*)&_functor) FunctorType( fc::forward<Functor>(f) ); **//FunctorType is a type of function? what's this?**
        _destroy_functor = &detail::functor_destructor<FunctorType>::destroy;
        _promise_impl = static_cast<promise<R>*>(this);
        _run_functor  = &detail::functor_run<FunctorType>::run;
      }
      virtual void cancel(const char* reason FC_CANCELATION_REASON_DEFAULT_ARG) override { task_base::cancel(reason); }
      aligned<FunctorSize> _functor;
    private:
      ~task(){}
  };

**Comment by mvandeberg** [comment] 2018-03-26 20:13
This is a part of the fc library that we are planning on moving away from and removing. From what I can tell, this is not a bug report, so I am closing the issue.

**Closed by mvandeberg** 2018-03-26 20:13 UTC
