### ISSUE TITLE
Tracking the converstion from SBD to STEEM

### ISSUE THREAD

**Issue by kurtr** [steemit/steem#459] opened 2016-09-22 23:39 UTC
5 days ago I did my first converstion from SBD to STEEM.

I am fully aware of the 7 day wait period but have noticed that there is no way to track the transaction via the wallet that I can find. Further the only evidence that I can find that the transaction *actually happened* is on steemd.com.

While I  know that the converstion will take place it concerns me that this will not be evident to new users and especially users who are also new to cryptocurrency and blockchains. I believe most new users will believe thier SBD has disappeared and think that the alt-coin is another scam.

Something as simple as a HISTORY entry in the wallet will fix this. i.e.

> 5 Days Ago     |     Converted 95 SBD to STEEM     |      **2 Days remaining**

**Comment by theoreticalbts** [comment] 2016-09-23 17:44
Duplicate of https://github.com/steemit/steemit.com/issues/260

**Closed by theoreticalbts** 2016-09-23 17:44 UTC
