### ISSUE TITLE
accessing steemit on web or esteem in smartphone is not sync

### ISSUE THREAD

**Issue by rizaofficial** [steemit/steem#2123] opened 2018-02-15 13:30 UTC
i have issues about upvote on steemit on web and esteem in smartphone is not sync, why i say like that?
because if we have upvote a some account content (post) in web, so we can't upvote in esteem, or at least we have a notification about we have upvote that account post. so that users is not confused anymore if users is upvote anymore and get a messeage like this:
![screenshot_2018-02-15-20-23-01-440_com netsolutions esteem](https://user-images.githubusercontent.com/36275394/36258732-638dd522-128e-11e8-9611-62ad489802ff.png)

And this is my sign that i have vote on web:
![inkedscreenshot_2018-02-15-20-19-13-177_com android chrome_li](https://user-images.githubusercontent.com/36275394/36258897-fd6315f4-128e-11e8-9785-7fe35272f9dd.jpg)

**Comment by mvandeberg** [comment] 2018-02-15 15:29
The Steem blockchain is a shared database that apps like Steemit.com, Esteem, Busy, etc. all use. Your actions are tracked across all the apps on the blockchain. By design, you cannot repeat your votes on another app. You can think of it like checking your email on your phone and in your browser. You expect reading and email in one location marks it read in the other. In the same way taking actions on Steemit.com are reflected in Esteem.

As this is not a problem with Steem, I am going to close this issue.

**Closed by mvandeberg** 2018-02-15 15:29 UTC
