### ISSUE TITLE
cli_wallet does not include necessary signatures computed from owner key for some transaction types leading to invalid transactions

### ISSUE THREAD

**Issue by arhag** [steemit/steem#165] opened 2016-07-15 08:50 UTC
According to user reports, someone who only has owner keys available to their cli_wallet cannot, for example, vote for witnesses from the cli_wallet. This problem seems to only be limited to the cli_wallet; apparently, users have reported that they can do these operations in the steemit.com GUI using only the owner keys.

I think the problem code is somewhere in this function (https://github.com/steemit/steem/blob/v0.9.0rc2/libraries/wallet/wallet.cpp#L528). I haven't yet figured out exactly what the issue is. But I think it is because the function inserts the keys from the active authority into `approving_key_set` because `req_active_approvals` is non-empty, but no keys from the owner authority are inserted because `req_owner_approvals` is empty. Thus, when it comes to this line (https://github.com/steemit/steem/blob/v0.9.0rc2/libraries/wallet/wallet.cpp#L645), no keys are added into `available_keys` and so the final transaction has no signatures.

From a quick glance at the code, I would think it would indicate that operations requiring only posting authority but cli_wallet only have active keys would give rise to similar bugs, but apparently posting/voting is fine via the cli_wallet with access to only active keys.

**Comment by arhag** [comment] 2016-07-16 11:30
> I would think it would indicate that operations requiring only posting authority but cli_wallet only have active keys would give rise to similar bugs, but apparently posting/voting is fine via the cli_wallet with access to only active keys.

I was wrong about the above. I can confirm that the same problem exists with active keys alone not being enough for vote and comment operations. The signatures field of the transaction are again empty, and in this case, it gives a `tx_missing_posting_auth` exception.

**Comment by abitmore** [comment] 2016-07-17 14:13
I think I've replied to this issue somewhere? It's not an issue of cli/gui, but of the node. But it's probably by design. What we need is an accurate specification document.

**Comment by theoreticalbts** [comment] 2016-08-17 19:14
I have code to fix this sitting around somewhere, I need to dig it out and merge it.

**Comment by theoreticalbts** [comment] 2017-11-27 20:48
This may be fixed by my code for #68.

**Comment by mvandeberg** [comment] 2018-07-27 00:09
Closing. Won't fix.

**Closed by mvandeberg** 2018-07-27 00:09 UTC
Labels: project/cli_wallet
