### ISSUE TITLE
Feature Suggestion: Revenue splitting from Curation Rewards

### ISSUE THREAD

**Issue by hrosspet** [steemit/steem#872] opened 2017-02-17 10:30 UTC
I would like to suggest a feature, which I think is essential for further growth of our platform:

**Allow 3rd party recommendation systems to take a percentage from curation rewards of their users.**

Short example: a user goes to steemrecommend.com where she finds a post she likes and proceeds to upvote the post through steemrecommend.com. The recommendation system asks her for permission to take a cut of a given % from her curation rewards and upvotes the post on her behalf. Once the payout of curation rewards for this upvote is due, they payout will be split according to the percentage between the user and steemrecommend.com.

The whole argument, why this feature is so important, plus initial discussion can be found [here](https://steemit.com/steemit/@hr1/feature-suggestion-revenue-splitting-from-curation-rewards) on Steem. It gained significant support from the community.

I found a mention about splitting curation rewards in this [issue](https://github.com/steemit/steem/issues/818#issuecomment-274487049). However, it seems that the technical difficulties described there are due to the delegation of steem power. I realize the difficulties, but I think that the simplest form of sharing curation rewards would be much simpler and is essential for managing the possible future increase in the numbers of posts created on Steem.

**Comment by aaroncox** [comment] 2017-02-17 10:41
It certainly would provide motive for 3rd party discovery platforms based on different metrics. 

I can't speak to what the LOE would be, but I imagine there would be some difficulties along the way.

**Comment by hrosspet** [comment] 2017-02-17 10:45
Probably the strongest point of the argument is that we shouldn't boost creation of new posts without also boosting their curation. It would cause imbalance and the result would be that nobody would be able to find the posts they like, or just a small fraction of them.

Boosting of new posts is addressed in Steemit 2017 Roadmap, more specificaly in the feature for sharing revenue from Author Rewards.

**Comment by mvandeberg** [comment] 2017-02-17 14:37
What you are describing is a curation guild. 

Reward splitting for author rewards is in 0.17.0 along with delegated SP. Delegated SP is actually all you need to write an app that implements curation guilds. While we agree that there are a lot of benefits to having guilds on the blockchain, there are far too many desired use cases for them for us to adequately implement them on the blockchain itself. Someone will feel left out that their model isn't supported. Or worse, we implement things in a way that prevents someone's model from working, even as app.

You create an app that tracks income from curation and then pays members dividends on those rewards. If there is some particular algorithm that becomes extremely popular, we might consider implementing it on the blockchain at that time. But for now it is possible to implement as a 3rd party app and we believe that is sufficient to support the growth of the Steem ecosystem in this area.

**Comment by hrosspet** [comment] 2017-02-17 15:13
@mvandeberg: Thanks for your response! I am not sure I understand it correctly:

Let's say I have the recommendation system described in OP. Are you suggesting that I should convince authors to post their content through my platform and charge them for the "increased visibility" resulting from my service instead of taking a cut directly from curators?

If that's what you meant, then I think it might be a viable business plan. I originally didn't realize that author rewards are just the other side of the same coin.

**Comment by mvandeberg** [comment] 2017-02-17 18:51
Author sides are the other side of the coin, but you could make a bot that follows votes of the accounts that have delegated to it and votes on the same content and then splits the rewards (after the power down) with all of the accounts that delegated to it.

**Comment by abitmore** [comment] 2017-02-18 23:36
@mvandeberg it's still a little different. One use case of this feature is voting software (aka curation bots). Powering down and splitting rewards with a bot requires active permission, but usually a voting software only have posting permission.

**Comment by hrosspet** [comment] 2017-02-19 19:43
@mvandeberg Thanks for the explanation, now I understand how SP delegation can be used for curation guilds.

However, as @abitmore described, SP delegation is really restrictive. Recommendation system (RS) as I suggest it could easily work under a pay per click business model (or pay a given percent from click's reward), so it offers a complete freedom for the user - e.g. make 3 upvotes through the RS and 37 by other means, which is obviously impossible under delegated SP system.

**Comment by hrosspet** [comment] 2017-02-19 19:46
I also revised my previous reply about the viability of the business model based on charging authors instead of curators. Now I am pretty sure this is not a viable option, or at least a very difficult one, because there is the chicken-egg problem. Authors don't have the incentive to join the RS before the RS has enough users and the RS can't bring the users if no authors are willing to publish there. The RS could start recommending authors from outside of the RS with the hope that they would join, but it seems to me as very unpredictable.

On the other hand, with a pay per click model the RS could start recommending right away and the only factor defining success would be the quality of its recommendations and consequently the number of users following its suggestions. Additionally, RS would be able to recommend articles even from first-time authors, who possibly wouldn't even know about the RS. That would not be possible when relying on the authors' side.

**Comment by liondani** [comment] 2017-03-08 12:57
First of all curation rewards must increase compared to author rewards!
Ratio 75:25 (author:curators) should be reversed and curators take the 75% cut.
Because curators are potentially thousands on each post (if we grow) but the author is only one.
I bet authors would agree since they would prefer to take 25% (why not even 10%?) from a big pie instead of 75% from "nothing"....

**Comment by mvandeberg** [comment] 2017-03-08 14:22
I am unsure what you are saying. If authors take a smaller percentage of the rewards on their posts, how will the pie become bigger?

**Comment by liondani** [comment] 2017-03-09 09:53
The idea behind it is that if you give more % to curators then steemit will attract MUCH more users that would be happy to power up. Because they will experience that they will get rewarded just by keeping active on the site (voting/curating) Even current whales would have a harder time to powerdown since it would have a meaning now to continue to vote for content. So if that is a serious reason to attract new users that would be our marketcap would grow.... What do you think authors would prefer? Getting 75% of rewards when steem sits on a $20M marketcap our 10%-25% when steem sits on a $1Billion market cap?

**Comment by abitmore** [comment] 2017-03-09 18:58
I have a feeling that the less the for-profit curators earn from voting on others' posts, the less willing they'll be to judge what posts are better which leads to bad curation, and the more likely they'll turn to vote for themselves. Just thinking out loud & could be wrong..

**Comment by xeroc** [comment] 2017-04-03 18:23
Given that there are no virtual operations for curation_rewards anymore, streemian.com cannot track the rewards caused by the service anymore. That makes it impossible for us to bill users a percentage of the curation rewards they earn by using streemian.com.
Is there a plan to reintroduce a feature that allows me to identify how much a specific vote has been paid out? Or maybe a list of payouts (author+curation) for a specific post?
If that feature is to disappear without replacement, I don't see that services like streemian can every earn a profits (except by (mis-)using the users voting power for auto-approval of sponsored posts)..

**Comment by abitmore** [comment] 2017-04-04 20:41
@xeroc I believe you have known that virtual operations are still there.

**Comment by mvandeberg** [comment] 2018-07-27 01:31
Closing, won't fix.

**Closed by mvandeberg** 2018-07-27 01:31 UTC
