### ISSUE TITLE
Assert Exception:is_valid_account_name( name ): Account name null is invalid

### ISSUE THREAD

**Issue by nnnarvaez** [steemit/steem#3270] opened 2019-03-31 08:04 UTC
When trying to transfer funds to `null` account from steem-python or cli_wallet the node replies:

from python:
```
assert_exception from 127.0.0.1 (Assert Exception:is_valid_account_name( name ): Account name null is invalid) in broadcast_transaction
```

from cli_wallet (`null` with no quotes)
```
10 assert_exception: Assert Exception
is_valid_account_name( name ): Account name  is invalid
    {"n":""}
    validation.hpp:19 validate_account_name

    {"*this":{"from":"initdreamer","to":"","amount":{"amount":"10000000","precision":3,"nai":"@@000000021"},"memo":"no Memo"}}
    steem_operations.cpp:191 validate

    {"from":"initdreamer","to":"","amount":"10000.000 DREAM","memo":"no Memo","broadcast":true}
    wallet.cpp:1864 transfer
``` 

from cli_wallet (`"null"` with quotes) 
```
10 assert_exception: Assert Exception
is_valid_account_name( name ): Account name null is invalid
    {"n":"null"}
    validation.hpp:19 validate_account_name

    {"*this":{"from":"initdreamer","to":"null","amount":{"amount":"10000000","pr                                                 ecision":3,"nai":"@@000000021"},"memo":"no Memo"}}
    steem_operations.cpp:191 validate

    {"from":"initdreamer","to":"null","amount":"10000.000 DREAM","memo":"no Memo                                                 ","broadcast":true}
    wallet.cpp:1864 transfer
unlocked >>> transfer initdreamer null "10000.000 DREAM" "no Memo" true
transfer initdreamer null "10000.000 DREAM" "no Memo" true

```

**Comment by mvandeberg** [comment] 2019-04-01 15:36
The null account is successfully receiving transfer on the Steem network and I double checked the validity of the null account in a unit test. This all seems to be working.

I also tested on a cli-wallet built for our testnet.

`unlocked >>> transfer "initminer" "null" "1000.000 TESTS" "" false`

```
{
  "ref_block_num": 30814,
  "ref_block_prefix": 3853958081,
  "expiration": "2019-04-01T15:35:21",
  "operations": [[
      "transfer",{
        "from": "initminer",
        "to": "null",
        "amount": "1000.000 TESTS",
        "memo": ""
      }
    ]
  ],
  "extensions": [],
  "signatures": [],
  "transaction_id": "fcd272906c7c69650b00809d5a1b6b57b82eef4c",
  "block_num": 0,
  "transaction_num": 0
}
```

The behavior of a `null` account defined by the empty string is correct, but I cannot reproduce the other behavior you are reporting. What branch of Steem are you building?

**Comment by nnnarvaez** [comment] 2019-04-03 05:53
Found the reason: STEEM_MIN_ACCOUNT_LENGTH value should remain at 3 (or 4 max) or rename the `temp` and `null` accounts to something longer if minimum account length is a thing you need.

**Comment by joticajulian** [comment] 2019-04-03 10:50
> It works, steemd is compiled with a value of 5 and cli_wallet with a value of 3

It works because null, temp and initminer are created in the genesis time, and in this function there is no validation.
If you want to increase the min length it is better to change the names of null and temp to be consistent.

**Comment by mvandeberg** [comment] 2019-04-03 15:24
> It works because null, temp and initminer are created in the genesis time, and in this function there is no validation.

All of these names pass validation. Transfers are made to the null and temp accounts, and those transactions must pass validation.

I am closing this because there is no bug in our code. Modifying our code may introduce bugs, but we are not responsible for fixing or diagnosing bugs that you have introduced. The context of this issue was misleading by not disclosing the fact that you were working with a modified version of our code.

**Closed by mvandeberg** 2019-04-03 15:24 UTC

**Comment by nnnarvaez** [comment] 2019-04-03 16:35
>  The context of this issue was misleading by not disclosing the fact that you were working with a modified version of our code.

Only code modified is values in 'config.cpp' and yes I should have mentioned it. 

Still if those names are a configurable setting is because they are susceptible of change and there is no validation of name length at Genesis  time so the accounts are created however they become unusable.

I agree if it's not broken don't fix it.
