### ISSUE TITLE
Better recovery of corrupt block_log

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1414] opened 2017-08-22 18:24 UTC
This ticket is to create an algorithm to detect and recover in case `block_log` is corrupt, without any changes to the `block_log` format.  A wishlist of what we want to do when/if we redesign the `block_log` format exists in #844.

Let's make some definitions:

- For any file offset, define the *maximum previous block offset* to be the current offset minus the minimum block size.
- Define the *minimum previous block offset* to be the current offset minus the maximum block size.
- A *candidate block_pos* is an offset for which the 8-byte sequence at that offset, when interpreted as `uint64_t` (little endian), is between the minimum previous block offset and the maximum previous block offset.
- A *candidate chain* is a sequence of candidate block_pos, where each element of the chain is the next element's previous value.
- A *candidate N-chain* is a sequence of candidate block_pos, which either has length `N`, or proceeds to the beginning of the file.
- A candidate chain is said to be *dense* if its blocks deserialize successfully with no overlap or extra space between them.
- A chain is said to be *cryptographically linked* if each block's hash matches the next block's `previous` member.

The algorithm works as follows:

- Fix N to be a `#define`'d constant.
- Start at the end of the file.
- Scan backwards until you encounter a candidate N-chain.  
- Verify this N-chain is dense.
- Verify this N-chain is cryptographically linked.

**Comment by theoreticalbts** [comment] 2017-11-27 22:19
I'm not going to be able to get to this for a while, so I'm removing my assignment.

If anyone takes this over, feel free to use [this very incomplete code](https://github.com/steemit/steem/tree/1414-wip-block-log-recovery) as a starting point.  Or just start over entirely.

**Comment by vogel76** [comment] 2018-02-23 12:26
It could be worth to consider using also RocksDB as a storage for these data. It offers sanity checks, indexed access (through block number, blockID, whatever you want), **data compression**, like also online data replication what can be used to dump given file to external location without a need to stop server (what is impossible atm).

**Comment by mvandeberg** [comment] 2018-03-02 18:25
The design of the block log was chosen so that it would be easily digestible by other libraries that know the steem protocol binary serialization (all steem libraries need to know this for signing). While placing it in RocksDB certainly has disadvantages and reading data from it by another process is not impossible, it would be difficult to do so without having access to a RocksDB library for that language.

**Comment by vogel76** [comment] 2018-03-26 15:48
Problem you are describing above is caused by missing well defined interface between internal data (like internal format of block held in local storage) and its public representation. Such thing could be quite good done ie by [gRPC ](https://grpc.io/) library, but this is rather part of discussion to be done here:
https://github.com/steemit/steem/issues/1964

**Comment by mvandeberg** [comment] 2018-08-30 16:54
Won't fix. Redesign is preferential #843 #844 #845

**Closed by mvandeberg** 2018-08-30 16:54 UTC
